{
 "title": "Base to Summit LInk - TEMPORARY",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Base to Summit Link - IN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "yaxes": [
    { "format": "decbps" }
   ],
   "targets": [
    {
     "alias": "100G-01-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(mean(\"ifHCInOctets\"), 10s) FROM \"snmp\" WHERE (\"agent_host\" = '10.48.1.4' AND \"ifName\" = 'Ethernet1/51') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "TELCONOR01- IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    },
    {
     "alias": "TELCONOR02- IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    }
   ]
  },
  {
   "title": "Summit Data Center Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "SDC_Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"temperature\")  / 10 FROM \"snmp\" WHERE (\"agent_host\" = '10.18.1.1') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Temperature 1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.18.1.1" }
     ]
    }
   ]
  },
  {
   "title": "Base to Summit Link - OUT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "yaxes": [
    { "format": "decbps" }
   ],
   "targets": [
    {
     "alias": "100G-01-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-02-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "TELCONOR01- OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1 /1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    },
    {
     "alias": "TELCONOR02- OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1 /1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    }
   ]
  },
  {
   "title": "Summit Data Center Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "SDC_Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"temperature\") -3 FROM \"snmp\" WHERE (\"agent_host\" = '10.17.0.254') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Temperature 1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.18.1.1" }
     ]
    }
   ]
  },
  {
   "title": "Total Base to Summit - IN",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "100G-01-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    }
   ]
  },
  {
   "title": "Total Base to Summit - OUT",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "100G-01-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-02-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    }
   ]
  },
  {
   "title": "Telconor IN",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Telconor01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    },
    {
     "alias": "Telconor02",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(mean(\"ifHCInOctets\"), 10s) FROM \"snmp\" WHERE (\"agent_host\" = '10.48.1.4' AND \"ifName\" = 'Ethernet1/48') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    }
   ]
  },
  {
   "title": "Telconor OUT",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Telconor01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    },
    {
     "alias": "Telconor02",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(mean(\"ifHCInOctets\"), 10s) FROM \"snmp\" WHERE (\"agent_host\" = '10.48.1.4' AND \"ifName\" = 'Ethernet1/48') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    }
   ]
  },
  {
   "title": "100G Base to Summit",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "100G-01-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-01-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-02-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    }
   ]
  },
  {
   "title": "Telconor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "TELCONOR - IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    },
    {
     "alias": "TELCONOR - OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    }
   ]
  },
  {
   "title": "LHN Monitoring",
   "type": "graph",
   "gridPos": { "h": 17, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "yaxes": [
    { "format": "decbps" }
   ],
   "targets": [
    {
     "alias": "LHN-01-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-01-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-02-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    }
   ]
  },
  {
   "title": "Telconor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "TELCONOR - IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(mean(\"ifHCInOctets\"), 10s) FROM \"snmp\" WHERE (\"agent_host\" = '10.48.1.5' AND \"ifName\" = 'Ethernet1/48') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    },
    {
     "alias": "TELCONOR - OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 1.3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    }
   ]
  },
  {
   "title": "LHN Monitoring",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 9, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "LHN-01-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-01-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-02-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    }
   ]
  }
 ]
}