{
 "title": "Ceph - Cluster",
 "description": "Ceph cluster overview",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_health_status, prom_cluster)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Health Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_health_status{prom_cluster=~'$cluster'}"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{prom_cluster=~'$cluster'})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{prom_cluster=~'$cluster'})",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{prom_cluster=~'$cluster'} == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{prom_cluster=~'$cluster'})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{prom_cluster=~'$cluster'} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{prom_cluster=~'$cluster'})",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mon_quorum_status{prom_cluster=~'$cluster'})",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 2
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{prom_cluster=~'$cluster'}) - sum(ceph_mon_quorum_status{prom_cluster=~'$cluster'})",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  {
   "title": "MGRs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mgr_status{prom_cluster=~'$cluster'} == 1) or vector(0)",
     "legendFormat": "Active",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Standby",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mgr_status{prom_cluster=~'$cluster'} == 0) or vector(0)",
     "legendFormat": "Standby",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used{prom_cluster=~'$cluster'})/sum(ceph_osd_stat_bytes{prom_cluster=~'$cluster'})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "PG States",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pg_total{prom_cluster=~'$cluster'})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(ceph_pg_active{prom_cluster=~'$cluster'})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(ceph_pg_total{prom_cluster=~'$cluster'} - ceph_pg_active{prom_cluster=~'$cluster'})",
     "legendFormat": "Inactive"
    },
    {
     "expr": "sum(ceph_pg_undersized{prom_cluster=~'$cluster'})",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum(ceph_pg_degraded{prom_cluster=~'$cluster'})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_inconsistent{prom_cluster=~'$cluster'})",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "sum(ceph_pg_down{prom_cluster=~'$cluster'})",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "OSD Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.95, ceph_osd_apply_latency_ms{prom_cluster=~'$cluster'})",
     "legendFormat": "Apply Latency P_95"
    },
    {
     "expr": "quantile(0.95, ceph_osd_commit_latency_ms{prom_cluster=~'$cluster'})",
     "legendFormat": "Commit Latency P_95"
    },
    {
     "expr": "avg(ceph_osd_apply_latency_ms{prom_cluster=~'$cluster'})",
     "legendFormat": "Avg Apply Latency"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{prom_cluster=~'$cluster'})",
     "legendFormat": "Avg Commit Latency"
    }
   ]
  },
  {
   "title": "Cluster I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{prom_cluster=~'$cluster'}[1m]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{prom_cluster=~'$cluster'}[1m]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "In-/Egress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": " Egress (-) / Ingress (+)" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(ceph_pool_stored{prom_cluster=~'$cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "OSD Capacity Utilization",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{prom_cluster=~'$cluster'} / ceph_osd_stat_bytes{prom_cluster=~'$cluster'}",
     "legendFormat": "Util (%)"
    }
   ]
  },
  {
   "title": "PGs per OSD",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "ceph_osd_numpg{prom_cluster=~'$cluster'}",
     "legendFormat": "#PGs"
    }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops", "label": "Recovery Ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{prom_cluster=~'$cluster'}[1m]))",
     "legendFormat": "Op/s"
    }
   ]
  }
 ]
}