{
 "title": "Deliverator / Summary",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "site",
    "query": {
     "query": "label_values(s3nd_upload_parts_active,site)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(s3nd_upload_parts_active{site=~\"$site\"},service)"
    }
   },
   { "name": "resolution", "query": "200ms" },
   { "name": "scrape_interval", "query": "100ms" }
  ]
 },
 "panels": [
  {
   "title": "Files Submitted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(s3nd_upload_valid_requests_total{site=~\"$site\", service=~\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Submitted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(s3nd_upload_bytes_total{site=~\"$site\", service=~\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Success",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  increase(s3nd_upload_http_requests_total{site=~\"$site\", service=~\"$service\", code=\"200\"}[$__range])\n) /\nsum (\n  increase(s3nd_upload_valid_requests_total{site=~\"$site\", service=~\"$service\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Transferred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  increase(s3nd_upload_bytes_total{site=~\"$site\", service=~\"$service\", code=\"200\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "active uploads",
   "type": "timeseries",
   "description": "Active uploads. Value may be an aggregate of multiple nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service) (\n  uploads{site=~\"$site\", service=~\"$service\"}\n  or\n  s3nd_upload_active{site=~\"$site\", service=~\"$service\"}\n  or\n  s3nd_upload_parts_active{site=~\"$site\", service=~\"$service\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Submitted",
   "type": "timeseries",
   "description": "Count of valid file upload requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service) (\n  increase(s3nd_upload_valid_requests_total{site=~\"$site\", service=~\"$service\"}[$__interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uploads moar detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (\n  increase(s3nd_upload_valid_requests_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "new requests"
    },
    {
     "expr": "sum (\n  uploads{site=~\"$site\", service=~\"$service\"}\n  or\n  s3nd_upload_active{site=~\"$site\", service=~\"$service\"}\n  or\n  s3nd_upload_parts_active{site=~\"$site\", service=~\"$service\"}\n)",
     "legendFormat": "active"
    },
    {
     "expr": "sum (\n  s3nd_upload_queued{site=~\"$site\", service=~\"$service\"}\n)",
     "legendFormat": "queued"
    },
    {
     "expr": "sum (\n  increase(s3nd_upload_attempts_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "attempts"
    },
    {
     "expr": "sum (\n  increase(s3nd_upload_retries_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "retries"
    },
    {
     "expr": "sum by(code,reason) (\n  increase(s3nd_upload_http_requests_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "{{code}}-{{reason}}"
    }
   ]
  },
  {
   "title": "Files Success/Failure",
   "type": "timeseries",
   "description": "The count of files successfully uploaded (or failed) to the S3 endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service) (\n  increase(s3nd_upload_http_requests_total{site=~\"$site\", service=~\"$service\", code=\"200\"}[$__interval])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "-1 * sum by(service) (\n  increase(s3nd_upload_http_requests_total{site=~\"$site\", service=~\"$service\", code!=\"200\"}[$__interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pacing Rate Per Conn",
   "type": "timeseries",
   "description": "The average packet pacing rate applied to tcp sockets.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "avg by (service) (\n  s3nd_s3_tcp_conn_pace_bytes{site=~\"$site\", service=~\"$service\"}\n  unless on (site, service, instance)\n  (s3nd_upload_parts_active{site=~\"$site\", service=~\"$service\"} == 0)\n) * 8",
     "legendFormat": "{{service}} active"
    },
    {
     "expr": "(sum by (service)(s3nd_s3_tcp_conn_pace_max_bytes{site=~\"$site\", service=~\"$service\"} ) ) *8",
     "legendFormat": "{{service}} max"
    }
   ]
  },
  {
   "title": "Bytes Sent Successfully",
   "type": "timeseries",
   "description": "The total number of bytes sent (file size) as part of a successful upload to the S3 endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (service) (\n  increase(s3nd_upload_bytes_total{site=~\"$site\", service=~\"$service\"}[$__interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "s3_http_responses",
   "type": "timeseries",
   "description": "HTTP status codes returned by the S3 endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service, code, reason) (\n  increase(s3nd_s3_http_responses_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "{{service}} {{code}}:{{reason}}"
    }
   ]
  },
  {
   "title": "tcp_info_bytes_sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_bytes_sent{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_bytes_sent_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "s3_api_errors",
   "type": "timeseries",
   "description": "AWS SDK API error codes from the S3 endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service, reason) (\n  increase(s3nd_s3_api_errors_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "{{service}} {{reason}}"
    }
   ]
  },
  {
   "title": "tcp_info_bytes_received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_bytes_received{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or    \n  irate(s3nd_s3_tcp_info_bytes_received_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "s3_tcp_conn",
   "type": "timeseries",
   "description": "TCP connections to the S3 endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service) (\n  s3nd_s3_tcp_conn_active{site=~\"$site\", service=~\"$service\"}\n)",
     "legendFormat": "{{service}} active"
    },
    {
     "expr": "sum by(service) (\n  increase(s3nd_s3_tcp_conn_closed_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "{{service}} closed"
    }
   ]
  },
  {
   "title": "tcp_info_bytes_acked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_bytes_acked{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_bytes_acked_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Duration: Successful",
   "type": "heatmap",
   "description": "The total duration of the request including any time queued waiting for upload slot(s).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(s3nd_upload_total_seconds{site=~\"$site\",service=~\"$service\", code=\"200\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_bytes_retrans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_bytes_retrans{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_bytes_retrans_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Duration: Failed",
   "type": "heatmap",
   "description": "The total duration of the request including any time queued waiting for upload slot(s).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(s3nd_upload_total_seconds{site=~\"$site\",service=~\"$service\", code!=\"200\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_total_retrans",
   "type": "timeseries",
   "description": "This might be a counter of retrans packets instead of bytes?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_total_retrans{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_total_retrans_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Duration: Successful",
   "type": "heatmap",
   "description": "The duration of actively attempting to upload a file, including retries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(s3nd_upload_transfer_seconds{site=~\"$site\",service=~\"$service\", code=\"200\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_sacked",
   "type": "timeseries",
   "description": "XXX What unit is this?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_sacked{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_sacked_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Duration: Failed",
   "type": "heatmap",
   "description": "The duration of actively attempting to upload a file, including retries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(s3nd_upload_transfer_seconds{site=~\"$site\",service=~\"$service\", code!=\"200\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_retrans",
   "type": "timeseries",
   "description": "XXX What unit is this?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_retrans{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_retrans_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Effective Transfer Rate Rer File",
   "type": "heatmap",
   "description": "The upload transfer data rate in bytes per seconds, including time spent retrying. Only successful uploads are counted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "sum(rate(s3nd_upload_transfer_rate_bytes{site=~\"$site\",service=~\"$service\"}[$__interval])*8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_lost",
   "type": "timeseries",
   "description": "XXX What unit is this?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_lost{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_lost_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File Size: Successful",
   "type": "heatmap",
   "description": "The distribution of file sizes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "sum(rate(s3nd_upload_transfer_size_bytes{site=~\"$site\",service=~\"$service\", code=\"200\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_reord_seen",
   "type": "timeseries",
   "description": "XXX What unit is this?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_reord_seen{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_reord_seen_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File Size: Failed",
   "type": "heatmap",
   "description": "The distribution of file sizes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "sum(rate(s3nd_upload_transfer_size_bytes{site=~\"$site\",service=~\"$service\", code!=\"200\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_rcv_ooopack",
   "type": "timeseries",
   "description": "XXX What unit is this?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_rcv_ooopack{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_rcv_ooopack_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued Duration: Successful",
   "type": "heatmap",
   "description": "Known to be buggy...",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum(rate(s3nd_upload_queued_seconds{site=~\"$site\",service=~\"$service\", code=\"200\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_fackets",
   "type": "timeseries",
   "description": "XXX What unit is this?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_fackets{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_fackets_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued Duration: Failed",
   "type": "heatmap",
   "description": "Known to be buggy...",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "sum(rate(s3nd_upload_queued_seconds{site=~\"$site\",service=~\"$service\", code!=\"200\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_dsack_dups",
   "type": "timeseries",
   "description": "XXX What unit is this?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum by(service) (\n  irate(tcp_info_dsack_dups{site=~\"$site\", service=~\"$service\"}[$resolution])\n  or\n  irate(s3nd_s3_tcp_info_dsack_dups_total{site=~\"$site\", service=~\"$service\"}[$resolution])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tcp_info_rtt",
   "type": "timeseries",
   "description": "tcpi_rtt from tcp_info in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(service) (s3nd_s3_tcp_info_rtt_seconds{site=~\"$site\", service=~\"$service\"} > 0)",
     "legendFormat": "{{service}} mean"
    },
    {
     "expr": "max by(service) (s3nd_s3_tcp_info_rtt_seconds{site=~\"$site\", service=~\"$service\"} > 0)",
     "legendFormat": "{{service}} max"
    },
    {
     "expr": "min by(service) (s3nd_s3_tcp_info_rtt_seconds{site=~\"$site\", service=~\"$service\"} > 0)",
     "legendFormat": "{{service}} min"
    }
   ]
  }
 ]
}