{
 "title": "Grafanomenal  Metricwatch 3000",
 "description": "up/down all hosts",
 "tags": [
  "kubernetes",
  "grafenomenal",
  "pdu",
  "overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Endpoints Up / Down ",
   "type": "stat",
   "description": "Testing all up/down all hosts.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"node-.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{job=\"blackbox-snmp-network\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Endpoints Down",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "up{job=~\"node-.*|blackbox-snmp-network\"} == 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL ",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"prometheus-blackbox-exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_http_ssl{job=~\"prometheus-blackbox-exporter\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=\"prometheus-blackbox-exporter\"} - time()) / 3600 / 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Principal",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xupsBatCapacity{instance=\"power-ups.cp.lsst.org\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UPS Auxtel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xupsBatCapacity{instance=\"aux-ups01.cp.lsst.org\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, max(measurementsExternalSensorValue{sensorID=\"1\"}) by (instance) / 10)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Postgres Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum(cnpg_collector_up{}) by (prom_cluster)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_info{container=\"postgres\"}) by (prom_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Principal Remaining Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xupsBatTimeRemaining{instance=\"power-ups.cp.lsst.org\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UPS Auxtel Remaining Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xupsBatTimeRemaining{instance=\"aux-ups01.cp.lsst.org\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LHN Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=\"new-rubinobs-br01.ls.lsst.org\",ifName=\"Ethernet1/1\"}[1m]) *8",
     "legendFormat": "In Primary"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"new-rubinobs-br01.ls.lsst.org\",ifName=\"Ethernet1/1\"}[1m]) *8",
     "legendFormat": "Out Primary"
    },
    {
     "expr": "rate(ifHCInOctets{instance=\"new-rubinobs-br02.ls.lsst.org\",ifName=\"Ethernet1/1\"}[1m]) *8",
     "legendFormat": "In Secondary"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"new-rubinobs-br02.ls.lsst.org\",ifName=\"Ethernet1/1\"}[1m]) *8",
     "legendFormat": "Out Secondary"
    }
   ]
  },
  {
   "title": "Summit - Base Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=\"new-rubinobs-br01.ls.lsst.org\",ifName=\"Ethernet13/1\"}[1m]) *8",
     "legendFormat": "In Control 1"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"new-rubinobs-br01.ls.lsst.org\",ifName=\"Ethernet13/1\"}[1m]) *8",
     "legendFormat": "Out Control 1"
    },
    {
     "expr": "rate(ifHCInOctets{instance=\"new-rubinobs-br02.ls.lsst.org\",ifName=\"Ethernet13/1\"}[1m]) *8",
     "legendFormat": "In Control 2"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"new-rubinobs-br02.ls.lsst.org\",ifName=\"Ethernet13/1\"}[1m]) *8",
     "legendFormat": "Out Control 2"
    },
    {
     "expr": "rate(ifHCInOctets{instance=\"new-rubinobs-br01.ls.lsst.org\",ifName=\"Ethernet17/1\"}[1m]) *8",
     "legendFormat": "In Science 1"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"new-rubinobs-br01.ls.lsst.org\",ifName=\"Ethernet17/1\"}[1m]) *8",
     "legendFormat": "Out Science 1"
    },
    {
     "expr": "rate(ifHCInOctets{instance=\"new-rubinobs-br01.ls.lsst.org\",ifName=\"Ethernet18/1\"}[1m]) *8",
     "legendFormat": "In Science 3"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"new-rubinobs-br01.ls.lsst.org\",ifName=\"Ethernet18/1\"}[1m]) *8",
     "legendFormat": "Out Science 3"
    },
    {
     "expr": "rate(ifHCInOctets{instance=\"new-rubinobs-br02.ls.lsst.org\",ifName=\"Ethernet17/1\"}[1m]) *8",
     "legendFormat": "In Science 2"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"new-rubinobs-br02.ls.lsst.org\",ifName=\"Ethernet17/1\"}[1m]) *8",
     "legendFormat": "Out Science 2"
    },
    {
     "expr": "rate(ifHCInOctets{instance=\"new-rubinobs-br02.ls.lsst.org\",ifName=\"Ethernet18/1\"}[1m]) *8",
     "legendFormat": "In Science 4"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"new-rubinobs-br02.ls.lsst.org\",ifName=\"Ethernet18/1\"}[1m]) *8",
     "legendFormat": "Out Science 4"
    },
    {
     "expr": "rate(ifHCInOctets{instance=\"sdc-a05-sp01.cp.lsst.org\",ifName=\"Ethernet65\"}[1m]) *8",
     "legendFormat": "In Telconor 1"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"sdc-a05-sp01.cp.lsst.org\",ifName=\"Ethernet65\"}[1m]) *8",
     "legendFormat": "Out Telconor 1"
    },
    {
     "expr": "rate(ifHCInOctets{instance=\"sdc-a06-sp02.cp.lsst.org\",ifName=\"Ethernet65\"}[1m]) *8",
     "legendFormat": "In Telconor 2"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"sdc-a06-sp02.cp.lsst.org\",ifName=\"Ethernet65\"}[1m]) *8",
     "legendFormat": "Out Telconor 2"
    }
   ]
  },
  {
   "title": "Dome Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=\"main6-as02.cp.lsst.org\",ifName=\"Ethernet1\"}[1m]) *8",
     "legendFormat": "In Eth1"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"main6-as02.cp.lsst.org\",ifName=\"Ethernet1\"}[1m]) *8",
     "legendFormat": "Out Eth1"
    },
    {
     "expr": "rate(ifHCInOctets{instance=\"main6-as02.cp.lsst.org\",ifName=\"Ethernet3\"}[1m]) *8",
     "legendFormat": "In Eth3"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"main6-as02.cp.lsst.org\",ifName=\"Ethernet3\"}[1m]) *8",
     "legendFormat": "Out Eth3"
    }
   ]
  },
  {
   "title": "Internet Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=\"bdc-b01-lf1\",ifName=\"Ethernet1/47\"}[1m]) *8",
     "legendFormat": "In Internet"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"bdc-b01-lf1\",ifName=\"Ethernet1/47\"}[1m]) *8",
     "legendFormat": "Out Internet"
    }
   ]
  },
  {
   "title": "Kubernetes Nodes Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})by (node)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Nodes CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\"}[2m])) by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})by (node)*100 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kubernetes Pods",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{job=\"kube-state-metrics\"}) by (namespace,prom_cluster)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{}) by (workload, namespace)) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(kube_pod_status_scheduled{condition=\"false\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{})\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max without(instance,node) (\n(\n  kubelet_volume_stats_capacity_bytes{}\n  -\n  kubelet_volume_stats_available_bytes{}\n)\n/\n  kubelet_volume_stats_capacity_bytes{}\n* 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}