{
 "title": "Interface overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "device",
    "query": {
     "query": "label_values(ifAdminStatus,instance)"
    }
   },
   {
    "name": "interface",
    "label": "interface",
    "query": {
     "query": "label_values(ifAdminStatus{instance=\"$instance\"},ifName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network data rate (bps - SI)",
   "type": "gauge",
   "description": "Data rates over the network device noted in bps and SI notations. TOTAL = IN + OUT \n\nHandy to check whether or not a switch is at capacity.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(ifHCInOctets{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval]))+sum(rate(ifHCOutOctets{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval])))*8",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum(rate(ifHCInOctets{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Network data rate (bps - SI)",
   "type": "timeseries",
   "description": "Data rates over the network device noted in bps and SI notations. \n\nHandy to check whether or not a switch is at capacity.",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "OUT"
    }
   ]
  },
  { "title": "Errors/discards/...", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Network error rate (pps) per interface",
   "type": "timeseries",
   "description": "Data rates over the network device noted in bps and SI notations. \n\nHandy to check whether or not a switch is at capacity.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(ifInErrors{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval])) by (ifName)*8",
     "legendFormat": "{{ifName}} in"
    },
    {
     "expr": "sum(rate(ifOutErrors{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval])) by (ifName)*8",
     "legendFormat": "{{ifName}} out"
    }
   ]
  },
  {
   "title": "Network discard rate (pps) per interface",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(ifInDiscards{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval])) by (ifName)*8",
     "legendFormat": "{{ifName}} in"
    },
    {
     "expr": "sum(rate(ifOutDiscards{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval])) by (ifName)*8",
     "legendFormat": "{{ifName}} out"
    }
   ]
  },
  {
   "title": "Network multicast rate (pps) per interface",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(ifInMulticastPkts{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval])) by (ifName)*8",
     "legendFormat": "{{ifName}} in"
    },
    {
     "expr": "sum(rate(ifOutMulticastPkts{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval])) by (ifName)*8",
     "legendFormat": "{{ifName}} out"
    }
   ]
  },
  {
   "title": "Network broadcast rate (pps) per interface",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(ifInBroadcastPkts{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval])) by (ifName)*8",
     "legendFormat": "{{ifName}} in"
    },
    {
     "expr": "sum(rate(ifOutBroadcastPkts{instance=~\"$instance\",ifName=\"$interface\"}[$__rate_interval])) by (ifName)*8",
     "legendFormat": "{{ifName}} out"
    }
   ]
  },
  { "title": "Interface status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Interface administrative status",
   "type": "status-history",
   "description": "The desired state of the interface. The testing(3) state indicates that no operational packets can be passed. When a managed system initializes, all interfaces start with ifAdminStatus in the down(2) state. As a result of either explicit management action or per configuration information retained by the managed system, ifAdminStatus is then changed to either the up(1) or testing(3) states (or remains in the down(2) state).",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "min_over_time(ifAdminStatus{instance=~\"$instance\",ifName=\"$interface\"}[$__interval])",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Interface operational status",
   "type": "status-history",
   "description": "The current operational state of the interface. The testing(3) state indicates that no operational packets can be passed. If ifAdminStatus is down(2) then ifOperStatus should be down(2). If ifAdminStatus is changed to up(1) then ifOperStatus should change to up(1) if the interface is ready to transmit and receive network traffic; it should change to dormant(5) if the interface is waiting for external actions (such as a serial line waiting for an incoming connection); it should remain in the down(2) state if and only if there is a fault that prevents it from going to the up(1) state; it should remain in the notPresent(6) state if the interface has missing (typically, hardware) components.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "min_over_time(ifOperStatus{instance=~\"$instance\",ifName=\"$interface\"}[$__interval])",
     "legendFormat": "{{ifName}}"
    }
   ]
  }
 ]
}