{
 "title": "Kubernetes / Logs",
 "description": "Logs collected from Kubernetes",
 "tags": [
  "kubernetes",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   {
    "name": "cluster",
    "query": {}
   },
   {
    "name": "namespace",
    "query": {}
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (namespace) (\n  count_over_time({job=\"k8s/logs\",cluster=\"$cluster\", namespace=~\"${namespace:regex}\"}[$__interval] |= \"$query\")\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (namespace) (\n  count_over_time({job=\"k8s/events\",cluster=\"$cluster\", namespace=~\"${namespace:regex}\"}[$__interval] |= \"$query\")\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (namespace) (\n  count_over_time({job=\"k8s/logs\",cluster=\"$cluster\", namespace=~\"$namespace\"}[$__range] |= \"$query\")\n)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (namespace) (\n  count_over_time({job=\"k8s/events\",cluster=\"$cluster\", namespace=~\"$namespace\"}[$__range] |= \"$query\")\n)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Bytes Stored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (namespace) (\n  bytes_over_time({job=~\"k8s/logs|k8s/events\",cluster=\"$cluster\", namespace=~\"$namespace\"}[$__range] |= \"$query\")\n)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "logs",
   "description": "Events",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"k8s/events\",namespace=~\"${namespace:regex}\", cluster=\"$cluster\"} |= \"$query\""
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"k8s/logs\",namespace=~\"${namespace:regex}\", cluster=\"$cluster\"} |= \"$query\""
    }
   ]
  }
 ]
}