{
 "title": "Kubernetes / Compute Resources / Throttling",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "k8s cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},prom_cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", prom_cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Throttling %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container!=\"\", prom_cluster=\"$cluster\"}[$__rate_interval])) by (pod) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container!=\"\", prom_cluster=\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", prom_cluster=\"$cluster\", container!=\"\"}) by (pod)/sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", prom_cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n)by(pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", prom_cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)/sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", prom_cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n)by(pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\"}) by (pod)\n"
    },
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\"}[5m])) by (pod) \n/ \nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n"
    },
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\"}[5m])) by (pod) \n/ \nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod)\n"
    },
    {
     "expr": "100*sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod) / sum(\n  kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}\n) by (pod)\n\n"
    },
    {
     "expr": "100*sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod) / sum(\n  kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}\n) by (pod)\n\n"
    }
   ]
  }
 ]
}