{
 "title": "Kyverno Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS_KYVERNO", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kyverno_policy_rule_info_total, prom_cluster)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Kyverno\nA Kubernetes-native policy management engine\n\n#### About this dashboard\n\nThis dashboard represents generic insights that can be extracted from a cluster with Kyverno running.\n\n#### For more details around the metrics\n\nCheckout the [official docs of Kyverno metrics](https://kyverno.io/docs/monitoring/)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rule Execution Failure Rate (Last 24 Hours)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_result=\"fail\",prom_cluster=\"$cluster\"}[24h]) or vector(0))*100/sum(increase(kyverno_policy_results_total[24h]))"
    }
   ]
  },
  {
   "title": "Cluster Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"cluster\",prom_cluster=\"$cluster\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"namespaced\",prom_cluster=\"$cluster\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Background Scans Failure Rate (Last 24 Hours)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{,prom_cluster=\"$cluster\"rule_result=\"fail\", policy_background_mode=\"true\",prom_cluster=\"$cluster\"}[24h]) or vector(0))*100/sum(increase(kyverno_policy_results_total{policy_background_mode=\"true\",prom_cluster=\"$cluster\"}[24h]))"
    }
   ]
  },
  {
   "title": "Validate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{rule_type=\"validate\",prom_cluster=\"$cluster\"}==1) by (rule_name))"
    }
   ]
  },
  {
   "title": "Mutate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{rule_type=\"mutate\",prom_cluster=\"$cluster\"}==1) by (rule_name))"
    }
   ]
  },
  {
   "title": "Generate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{rule_type=\"generate\",prom_cluster=\"$cluster\"}==1) by (rule_name))"
    }
   ]
  },
  {
   "title": "Policy-Rule Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Admission Review Results (per-rule)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_execution_cause=\"admission_request\",prom_cluster=\"$cluster\"}[5m])) by (rule_result)",
     "legendFormat": "Admission Review Result: {{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-rule)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_execution_cause=\"background_scan\",prom_cluster=\"$cluster\"}[5m])) by (rule_result)",
     "legendFormat": "Background Scan Result: {{rule_result}}"
    }
   ]
  },
  {
   "title": "Policy Failures",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(increase(kyverno_policy_results_total{rule_result=\"fail\",prom_cluster=\"$cluster\"}[5m])) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  {
   "title": "Admission Review Results (per-policy)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(increase(kyverno_policy_results_total{rule_execution_cause=\"admission_request\",prom_cluster=\"$cluster\"}[5m])) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "Admission Review Result: {{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-policy)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(increase(kyverno_policy_results_total{rule_execution_cause=\"background_scan\",prom_cluster=\"$cluster\"}[5m])) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "Background Scan Result: {{rule_result}}"
    }
   ]
  },
  {
   "title": "Policy-Rule Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Policies (by policy type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{prom_cluster=\"$cluster\"}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Policies (by policy validation action)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{prom_cluster=\"$cluster\"}==1) by (policy_name, policy_validation_mode)) by (policy_validation_mode)",
     "legendFormat": "Policy Validation Mode: {{policy_validation_mode}}"
    }
   ]
  },
  {
   "title": "Active Policies running in background mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_background_mode=\"true\",prom_cluster=\"$cluster\"}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Namespaced Policies (by namespaces)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_namespace!=\"-\",prom_cluster=\"$cluster\"}==1) by (policy_name, policy_namespace)) by (policy_namespace)",
     "legendFormat": "Namespace: {{policy_namespace}}"
    }
   ]
  },
  {
   "title": "Active Rules (by rule type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{prom_cluster=\"$cluster\"}==1) by (rule_type, rule_name)) by (rule_type)",
     "legendFormat": "Rule Type: {{rule_type}}"
    }
   ]
  },
  {
   "title": "Policy-Rule Execution Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Rule Execution Latency Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_policy_execution_duration_seconds_sum{prom_cluster=\"$cluster\"}[5m])) by (rule_type) / sum(rate(kyverno_policy_execution_duration_seconds_count[5m])) by (rule_type)",
     "legendFormat": "Rule Type: {{rule_type}}"
    }
   ]
  },
  {
   "title": "Average Policy Execution Latency Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_policy_execution_duration_seconds_sum{prom_cluster=\"$cluster\"}[5m])) by (policy_type) / sum(rate(kyverno_policy_execution_duration_seconds_count[5m])) by (policy_type)",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  {
   "title": "Overall Average Rule Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_execution_duration_seconds_sum{prom_cluster=\"$cluster\"}) / sum(kyverno_policy_execution_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Overall Average Policy Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{prom_cluster=\"$cluster\"}) by (policy_name, policy_type) / sum(kyverno_policy_execution_duration_seconds_count) by (policy_name, policy_type))"
    }
   ]
  },
  {
   "title": "Admission Review Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg - Admission Review Duration Over Time (by operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_review_duration_seconds_sum{prom_cluster=\"$cluster\"}[5m])) by (resource_request_operation) / sum(rate(kyverno_admission_review_duration_seconds_count[5m])) by (resource_request_operation)",
     "legendFormat": "Resource Operation: {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Avg - Admission Review Duration Over Time (by resource kind)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_review_duration_seconds_sum{prom_cluster=\"$cluster\"}[5m])) by (resource_kind) / sum(rate(kyverno_admission_review_duration_seconds_count[5m])) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Rate - Incoming Admission Requests (per 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total{prom_cluster=\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Avg - Overall Admission Review Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_admission_review_duration_seconds_sum{prom_cluster=\"$cluster\"})/sum(kyverno_admission_review_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Policy Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Changes Over Time (by change type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_changes_total{prom_cluster=\"$cluster\"}[5m])) by (policy_change_type)",
     "legendFormat": "Change type: {{policy_change_type}}"
    }
   ]
  },
  {
   "title": "Policy Changes Over Time (by policy type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_changes_total{prom_cluster=\"$cluster\"}[5m])) by (policy_type)",
     "legendFormat": "Policy Type: {{policy_type}}"
    }
   ]
  },
  {
   "title": "Total Policy Changes (Last 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_changes_total{prom_cluster=\"$cluster\"}[24h]))"
    }
   ]
  },
  {
   "title": "Rate - Policy Changes Happening (last 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_policy_changes_total{prom_cluster=\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Admission Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Admission Requests (by operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total{prom_cluster=\"$cluster\"}[5m])) by (resource_request_operation)",
     "legendFormat": "Resource Operation: {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Admission Requests (by resource kind)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total{prom_cluster=\"$cluster\"}[5m])) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Total Admission Requests (Last 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total{prom_cluster=\"$cluster\"}[24h]))"
    }
   ]
  }
 ]
}