{
 "title": "LSSTCAM Networking",
 "description": "Networking plots for the LSSTCAM cluster",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Traffic Transmission Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"lsstcam.*\", job=\"node-puppetdb\", environment=\"cp_production\", site=\"cp\", device=~\"eno1|enp1s0|enp2s0|lo|ens1f0np0\"}[$__interval]) * 8",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Receiving Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"lsstcam.*\", job=\"node-puppetdb\", environment=\"cp_production\", site=\"cp\", device=~\"eno1|enp1s0|enp2s0|lo|ens1f0np0\"}[$__interval]) * 8",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "UDP SndBuf Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=~\"lsstcam.*\", job=\"node-puppetdb\", environment=\"cp_production\", site=\"cp\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UDP RcvBuf Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=~\"lsstcam.*\", job=\"node-puppetdb\", environment=\"cp_production\", site=\"cp\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UDP In Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"lsstcam.*\", job=\"node-puppetdb\", environment=\"cp_production\", site=\"cp\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UDP Lite In Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{instance=~\"lsstcam.*\", job=\"node-puppetdb\", environment=\"cp_production\", site=\"cp\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "UDP Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } }
 ]
}