{
 "title": "Monitor UPS",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "2023-01-30T03:00:00.000Z", "to": "2023-02-01T02:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "inter",
    "label": "Interval",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d,60d,90d"
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   }
  ]
 },
 "panels": [
  {
   "title": "Accumulated Energy - Active Energy Delivered ",
   "type": "graph",
   "description": "22-Jul-2016 07:23:17 ( GMT )",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Energy Delivered ",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Accumulated Energy - Active Energy Delivered"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Energy - Reactive Energy Delivered",
   "type": "stat",
   "description": "22-Jul-2016 07:23:17 ( GMT )",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Accumulated Energy - Reactive Energy Delivered"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Energy - Active Energy Delivered ",
   "type": "stat",
   "description": "22-Jul-2016 07:23:17 ( GMT )",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Accumulated Energy - Apparent Energy Delivered"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ups01-Battery percent charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-Battery run time in seconds before UPS to low battery"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  { "title": "DP01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Load Current Ia",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase A" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Current Ia",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase A" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Current Ic",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Active Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Active Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Reactive Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Reactive Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Apparent Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Apparent Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vab ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured Line Voltage - Vab" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vbc ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured Line Voltage - Vbc" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vca",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured Line Voltage - Vca" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Van",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVan" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vbn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVbn" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vcn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVcn" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "vVan",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVan" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "vVbn",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVbn" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "vVcn",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVcn" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Phase A",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase B",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase C",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MQTT Test",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-input frequency in tenths of Hz"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "telegrafMQTT/iot-gw/snmp" }
     ]
    }
   ]
  },
  {
   "title": "Measured Neutral Current",
   "type": "graph",
   "description": "Measured Neutral Current - (Amps)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Measured Neutral Current",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured Neutral Current" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured System Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "alias": "Measured System Frequency",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured System Frequency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reactive Power ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "yaxes": [
    { "format": "kvoltampreact" }
   ],
   "targets": [
    {
     "alias": "Phase A",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Reactive Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase B",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Reactive Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase C",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Reactive Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Phase A",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase B",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase C",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Active power Phase A",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase C" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Apparent Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "yaxes": [
    { "format": "kvoltamp" }
   ],
   "targets": [
    {
     "alias": "Phase A",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase B",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase C",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Active Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Apparent Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor - Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Active Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Apparent Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor - Phase A",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase A" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor - Phase B",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase B" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor - Phase C",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase C" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE (\"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "UPS PRINCIPAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "UPS Battery Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ups01-Battery percent charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-Battery run time in seconds before UPS to low battery"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-Battery Current as reported"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-Battery voltage as reported by the UPS meters"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-ambient temperature in the vicinity of the UPS or SNMP agent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ups01-status battery" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Input L1 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Real Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Input L1 ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "ByPass",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Input L1 ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Voltage ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Output L1 Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Output L1 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Real Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Output L1 ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-input frequency in tenths of Hz"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  { "title": "UPS AUX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "UPS Battery Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ups02-Battery percent charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-Battery run time in seconds before UPS to low battery"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-Battery voltage as reported by the UPS meters"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-ambient temperature in the vicinity of the UPS or SNMP agent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Input L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Input L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Watts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Input L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-input frequency in tenths of Hz"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Output L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Output L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Watts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Output L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-output frequency in tenths of Hz"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bypass Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Bypass L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Bypass L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Bypass L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "SYSTEM - CPU, Memory, Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage per core",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_cpu",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" =~ /cpu[0-9].*/ AND \"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"cpu\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 141 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "mem_inactive",
       "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 148 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 148 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "system_load1",
       "query": "SELECT mean(load1) as load1,mean(load5) as load5,mean(load15) as load15 FROM \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT mean(running) as running, mean(blocked) as blocked, mean(sleeping) as sleeping, mean(stopped) as stopped, mean(zombies) as zombies, mean(paging) as paging, mean(unknown) as unknown FROM \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 },
   "collapsed": true,
   "panels": [
    {
     "title": "Root Disk usage (/)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_path : $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_total",
       "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\", mean(free) as \"free\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "All partitions usage (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_path ($tag_fstype on $tag_device)",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_total",
       "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"path\", \"device\", \"fstype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Root (/) Disk inodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_path : $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_total) as \"total\", mean(inodes_free) as \"free\", mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "All partitions Inodes (Free)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_path ($tag_fstype on $tag_device)",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_total",
       "query": "SELECT mean(\"inodes_free\") AS \"free\" FROM \"disk\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"path\", \"device\", \"fstype\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT mean(free) as \"free\", mean(used) as \"used\", mean(total) as \"total\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap I/O bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT mean(\"in\") as \"in\", mean(\"out\") as \"out\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"in\"  FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$interface/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$interface/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 159 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$interface/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$interface/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TCP connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 167 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT mean(tcp_close) as CLOSED, mean(tcp_close_wait) as CLOSE_WAIT, mean(tcp_closing) as CLOSING, mean(tcp_established) as ESTABLISHED, mean(tcp_fin_wait1) as FIN_WAIT1, mean(tcp_fin_wait2) as FIN_WAIT2, mean(tcp_last_ack) as LAST_ACK, mean(tcp_syn_recv) as SYN_RECV, mean(tcp_syn_sent) as SYN_SENT, mean(tcp_time_wait) as TIME_WAIT FROM \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TCP handshake issues",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(tcp_outrsts), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(tcp_activeopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(tcp_passiveopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Packets Drop",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "yaxes": [
      { "format": "short", "label": "Packets drop" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(drop_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$interface/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(drop_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$interface/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Packets Error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
     "yaxes": [
      { "format": "short", "label": "Packets drop" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(err_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$interface/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(err_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$interface/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}