{
 "title": "Network / Node",
 "tags": [ "network" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "query", "label": "Search query" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifAdminStatus,instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(up{instance=\"$instance\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs Overtime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"network\",host=\"$host\"}[$__interval])",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"network\",host=\"$host\"} |= \"$query\""
    }
   ]
  },
  {
   "title": "Uptime Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} / 100 / 3600",
     "legendFormat": "Hours"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} / 100 / 86400",
     "legendFormat": "__auto"
    },
    {
     "expr": "sysUpTime{instance=\"$instance\"} / 100 /3600\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$instance\"}[5m]) *8",
     "legendFormat": "{{ifName}}-{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "up{instance='$instance',job=\"blackbox-snmp-network\"}",
     "legendFormat": "Up/Down"
    },
    {
     "expr": "probe_icmp_duration_seconds{instance='$instance',phase=\"rtt\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"$instance\"}[5m]) *8",
     "legendFormat": "{{ifName}}-{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifInDiscards{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ifName}}-{{ifAlias}}"
    },
    {
     "expr": "rate(ifOutDiscards{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ifName}}-{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifInErrors{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ifName}}-{{ifAlias}}"
    },
    {
     "expr": "rate(ifOutErrors{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ifName}}-{{ifAlias}}"
    }
   ]
  }
 ]
}