{
 "title": "Network / Node / Port",
 "tags": [ "network" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(ifAdminStatus,instance)"
    }
   },
   {
    "name": "port",
    "label": "port",
    "query": {
     "query": "label_values(ifAdminStatus{instance=\"$instance\"},ifName)"
    }
   },
   {
    "name": "description",
    "label": "description",
    "query": {
     "query": "label_values(ifAdminStatus{instance=\"$instance\", ifName=\"$port\"},ifAlias)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "text", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 }, "options": { "content": "# ${description:empty}\n" } },
  {
   "title": "Admin Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$instance\",ifName=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operational Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$instance\",ifName=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed{instance=\"$instance\", ifName=\"$port\" } * 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{instance=\"$instance\",ifName=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"$instance\",ifName=\"$port\"}[5m]) *8",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$instance\",ifName=\"$port\"}[5m]) *8",
     "legendFormat": "OutBound"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifInErrors{instance=\"$instance\",ifName=\"$port\"}[5m])",
     "legendFormat": "InErrors"
    },
    {
     "expr": "rate(ifOutErrors{instance=\"$instance\",ifName=\"$port\"}[5m])",
     "legendFormat": "OutErrors"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(ifInDiscards{instance=\"$instance\",ifName=\"$port\"}[5m])",
     "legendFormat": "InDiscards"
    },
    {
     "expr": "rate(ifOutDiscards{instance=\"$instance\",ifName=\"$port\"}[5m])",
     "legendFormat": "OutDiscards"
    }
   ]
  },
  {
   "title": "Broadcast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInBroadcastPkts{instance=\"$instance\",ifName=\"$port\"}[5m])",
     "legendFormat": "InBroadcast"
    },
    {
     "expr": "rate(ifHCOutBroadcastPkts{instance=\"$instance\",ifName=\"$port\"}[5m])",
     "legendFormat": "OutBroadcast"
    }
   ]
  },
  {
   "title": "Multicast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInMulticastPkts{instance=\"$instance\",ifName=\"$port\"}[5m])",
     "legendFormat": "InMulticast"
    },
    {
     "expr": "rate(ifHCOutMulticastPkts{instance=\"$instance\",ifName=\"$port\"}[5m])",
     "legendFormat": "OutMulticast"
    }
   ]
  }
 ]
}