{
 "title": "PDU / Details",
 "tags": [
  "pdu",
  "power",
  "details"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pdu",
    "label": "PDU",
    "query": {
     "query": "label_values(measurementsExternalSensorValue, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PDU Total Utilization",
   "type": "gauge",
   "description": "PDU total utilization percentage based on current",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(measurementsOutletSensorSignedValue{instance=\"$pdu\", outletId=~\"[1-9]|[1-4][0-8]\", sensorType=\"rmsCurrent\"} > 0) / 16000 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical Outlets Alert",
   "type": "stat",
   "description": "Number of outlets with high utilization (>70% of historical maximum)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  measurementsOutletSensorSignedValue{instance=\"$pdu\", outletId=~\"[1-9]|[1-4][0-8]\", sensorType=\"rmsCurrent\"} > 0\n  and\n  measurementsOutletSensorSignedValue{instance=\"$pdu\", outletId=~\"[1-9]|[1-4][0-8]\", sensorType=\"rmsCurrent\"} / \n  measurementsOutletSensorMaxValue{instance=\"$pdu\", outletId=~\"[1-9]|[1-4][0-8]\", sensorType=\"rmsCurrent\"} > 0.7\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Power Factor",
   "type": "stat",
   "description": "Average power factor of all active outlets",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  measurementsOutletSensorSignedValue{instance=\"$pdu\", outletId=~\"[1-9]|[1-4][0-8]\", sensorType=\"powerFactor\"} > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature $pdu",
   "type": "stat",
   "description": "temperature measured on the front of the rack. ",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$pdu\", sensorID=\"1\"} / 10",
     "legendFormat": "Front"
    },
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$pdu\", sensorID=\"3\"} / 10",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Humidity $pdu",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$pdu\", sensorID=\"2\"}",
     "legendFormat": "Front"
    },
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$pdu\", sensorID=\"4\"}",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Active Energy History",
   "type": "timeseries",
   "description": "Total active power consumption over time",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(measurementsOutletSensorSignedValue{instance=\"$pdu\", outletId=~\"[1-9]|[1-4][0-8]\", sensorType=\"activePower\"})",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Top 8 Outlets Power Comparison",
   "type": "bargauge",
   "description": "Top 8 outlets with highest active power consumption",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, max(measurementsOutletSensorSignedValue{instance=\"$pdu\",sensorType=\"activePower\"}) by (outletId))",
     "legendFormat": "Outlet {{outletId}}"
    }
   ]
  },
  {
   "title": "Top 8 Outlets Current Comparison",
   "type": "bargauge",
   "description": "Top 8 outlets with highest active power consumption",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, max(measurementsOutletSensorSignedValue{instance=\"$pdu\",sensorType=\"rmsCurrent\"}/1000) by (outletId))",
     "legendFormat": "Outlet {{outletId}}"
    }
   ]
  },
  {
   "title": "Outlet Active Power",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"1\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"2\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"3\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"4\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"5\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"6\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"7\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"8\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"9\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"10\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"11\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"12\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"13\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"14\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"15\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"16\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"17\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"18\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"19\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"20\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"21\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"22\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"23\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"24\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"25\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"26\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"27\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"28\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"29\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"30\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"31\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"32\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"33\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"34\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"35\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"36\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"37\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"38\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"39\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"40\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"41\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"42\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"43\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"44\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"45\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"46\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"47\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"48\",sensorType=\"activePower\"}",
     "legendFormat": "Outlet {{outletId}}"
    }
   ]
  },
  {
   "title": "RMS Current",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"1\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"2\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"3\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"4\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"5\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"6\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"7\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"8\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"9\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"10\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"11\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"12\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"13\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"14\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"15\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"16\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"17\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"18\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"19\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"20\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"21\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"22\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"23\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"24\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"25\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"26\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"27\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"28\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"29\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"30\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"31\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"32\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"33\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"34\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"35\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"36\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"37\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"38\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"39\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"40\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"41\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"42\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"43\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"44\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"45\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"46\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"47\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    },
    {
     "expr": "measurementsOutletSensorValue{instance=\"$pdu\",outletId=\"48\",sensorType=\"rmsCurrent\"}/1000",
     "legendFormat": "Outlet {{outletId}}"
    }
   ]
  },
  {
   "title": "Outlet Heat Map",
   "type": "heatmap",
   "description": "Active power distribution by outlet over time",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "measurementsOutletSensorSignedValue{instance=\"$pdu\", outletId=~\"[1-9]|[1-4][0-8]\", sensorType=\"activePower\"}",
     "legendFormat": "{{outletId}}"
    }
   ]
  }
 ]
}