{
 "title": "PDU / Overview",
 "tags": [
  "pdu",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(measurementsExternalSensorValue, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Back Temperature",
   "type": "stat",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"3\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Front Temp. $instance",
   "type": "stat",
   "description": "temperature measured on the front of the rack. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"1\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Back Temp. $instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"3\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity $instance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"2\"}",
     "legendFormat": "Front"
    },
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"4\"}",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Rack Doors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Water Detector",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InLet Active Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsInletSensorValue{inletId=\"1\", instance=\"$instance\", pduId=\"1\", sensorType=\"activePower\"}/1000",
     "legendFormat": "Front"
    }
   ]
  },
  {
   "title": "Outlet Active Power",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(measurementsOutletSensorValue{instance=\"$instance\",outletId=~\"[1-9]|1[0-6]\",sensorType=\"rmsCurrent\"}/1000)",
     "legendFormat": "L1"
    },
    {
     "expr": "sum(measurementsOutletSensorValue{instance=\"$instance\",outletId=~\"1[7-9]|2[0-9]|3[0-2]\",sensorType=\"rmsCurrent\"}/1000)\n",
     "legendFormat": "L2"
    },
    {
     "expr": "sum(measurementsOutletSensorValue{instance=\"$instance\",outletId=~\"3[2-9]|4[0-8]\",sensorType=\"rmsCurrent\"}/1000)\n",
     "legendFormat": "L3"
    }
   ]
  }
 ]
}