{
 "title": "PDUs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(measurementsExternalSensorValue, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Back Temperature",
   "type": "stat",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"3\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Front Temp. $instance",
   "type": "stat",
   "description": "temperature measured on the front of the rack. ",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"1\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Back Temperature $instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"3\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity $instance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"2\"}",
     "legendFormat": "Front"
    },
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"4\"}",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Rack Doors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Water Detector",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "measurementsExternalSensorValue{instance=~\"$instance\", sensorID=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}