{
 "title": "Power / Overview",
 "tags": [
  "power",
  "ups",
  "overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Commercial Grid Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(xupsBypassVoltage{xupsBypassPhase=~\"1|2|3\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Principal Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatCapacity{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ups01-Battery percent charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Principal Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatTimeRemaining{instance=\"power-ups.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-Battery run time in seconds before UPS to low battery"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Principal Temperature ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsEnvAmbientTemp{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-ambient temperature in the vicinity of the UPS or SNMP agent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Principal Volt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatVoltage{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-Battery voltage as reported by the UPS meters"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Auxtel Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xupsBatCapacity{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ups02-Battery percent charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Auxtel Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatTimeRemaining{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-Battery run time in seconds before UPS to low battery"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Auxtel Temperature ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsEnvAmbientTemp{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-ambient temperature in the vicinity of the UPS or SNMP agent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Auxtel Volt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatVoltage{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-Battery voltage as reported by the UPS meters"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "DP01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Load Current Ia",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lcIa{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase A" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Van",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vVan{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVan" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vab ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vVab{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured Line Voltage - Vab" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Active Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pActivePtot{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Active Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Phase A",
     "expr": "lcIa{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase A",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase B",
     "expr": "lcIb{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase B",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase C",
     "expr": "lcIC{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase C",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Current Ib",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lcIb{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase B" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vbn",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vVbn{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVbn" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vca",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vVbc{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured Line Voltage - Vca" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Reactive Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pReactivePtot{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Reactive Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Current Ic",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lcIC{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vcn",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vVcn{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVcn" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line - Vbc ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vVca{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured Line Voltage - Vbc" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Apparent Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pApparentPtot{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Apparent Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Line Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "vVan",
     "expr": "vVan{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "vVan",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVan" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "vVbn",
     "expr": "vVbn{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "vVbn",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVbn" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "vVcn",
     "expr": "vVcn{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "vVcn",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "vVcn" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor - Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pActivePtot{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Active Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "expr": "pApparentPtot{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Apparent Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor - Phase A",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pActivePa{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "expr": "pApparentPa{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase A" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor - Phase B",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pActivePb{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "expr": "pApparentPb{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase B" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor - Phase C",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pActivePc{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase C" ], "type": "field" }
      ]
     ]
    },
    {
     "expr": "pApparentPc{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Neutral Current",
   "type": "timeseries",
   "description": "Measured Neutral Current - (Amps)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Measured Neutral Current",
     "expr": "lcIn{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Measured Neutral Current",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured Neutral Current" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Phase A",
     "expr": "pActivePa{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase A",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase B",
     "expr": "pActivePb{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase B",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase C",
     "expr": "pActivePc{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase C",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Active power Phase A",
     "expr": "pActivePa{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "expr": "pApparentPa{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Active Power - Phase C" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reactive Power ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "targets": [
    {
     "alias": "Phase A",
     "expr": "pReactivePa{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase A",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Reactive Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase B",
     "expr": "pReactivePb{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase B",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Reactive Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase C",
     "expr": "pReactivePc{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase C",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Reactive Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pActivePtot{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Active Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "expr": "pApparentPtot",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Total Apparent Power - Phase (A,B,C)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Apparent Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "alias": "Phase A",
     "expr": "pApparentPa{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase A",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase A" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase B",
     "expr": "pApparentPb{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase B",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase B" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Phase C",
     "expr": "pApparentPc{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Phase C",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Apparent Power - Phase C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Energy - Active Energy Delivered ",
   "type": "timeseries",
   "description": "22-Jul-2016 07:23:17 ( GMT )",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Energy Delivered ",
     "expr": "aeActiveEDelivered{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "Energy Delivered",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Accumulated Energy - Active Energy Delivered"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured System Frequency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "alias": "Measured System Frequency",
     "expr": "fFrequency{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "Measured System Frequency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Energy - Active Energy Delivered ",
   "type": "stat",
   "description": "22-Jul-2016 07:23:17 ( GMT )",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aeActiveEDelivered{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Accumulated Energy - Apparent Energy Delivered"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Energy - Reactive Energy Delivered",
   "type": "stat",
   "description": "22-Jul-2016 07:23:17 ( GMT )",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aeReactiveEDelivered{instance=\"power-dp01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "Accumulated Energy - Reactive Energy Delivered"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  { "title": "UPS PRINCIPAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "UPS Battery Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatCapacity{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ups01-Battery percent charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatTimeRemaining{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-Battery run time in seconds before UPS to low battery"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatCurrent{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-Battery Current as reported"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatVoltage{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-Battery voltage as reported by the UPS meters"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsEnvAmbientTemp{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-ambient temperature in the vicinity of the UPS or SNMP agent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xupsBatteryAbmStatus{instance=\"power-ups.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ups01-status battery" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "xupsInputVoltage{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Input L1 Current",
     "expr": "xupsInputCurrent{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Real Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Input L1 ",
     "expr": "xupsInputWatts{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "ByPass",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Input L1 ",
     "expr": "xupsBypassVoltage{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups01-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Voltage ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Output L1 Voltage",
     "expr": "xupsOutputVoltage{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Output L1 Current",
     "expr": "xupsOutputCurrent{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Real Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Output L1 ",
     "expr": "xupsOutputWatts{instance=\"power-ups.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups01-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "xupsInputFrequency{instance=\"power-ups.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups01-input frequency in tenths of Hz"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  { "title": "UPS AUX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "UPS Battery Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatCapacity{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ups02-Battery percent charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatTimeRemaining{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-Battery run time in seconds before UPS to low battery"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsBatVoltage{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-Battery voltage as reported by the UPS meters"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "xupsEnvAmbientTemp{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-ambient temperature in the vicinity of the UPS or SNMP agent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Input L1",
     "expr": "xupsInputVoltage{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Input L1",
     "expr": "xupsInputCurrent{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Watts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Input L1",
     "expr": "xupsInputCurrent{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-input",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "xupsInputFrequency{instance=\"aux-ups01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-input frequency in tenths of Hz"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Output L1",
     "expr": "xupsOutputVoltage{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Output L1",
     "expr": "xupsOutputCurrent{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Watts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Output L1",
     "expr": "xupsOutputWatts{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-output",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "xupsOutputFrequency{instance=\"aux-ups01.cp.lsst.org\"}",
     "legendFormat": "__auto",
     "measurement": "snmp",
     "select": [
      [
       {
        "params": [
         "ups02-output frequency in tenths of Hz"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bypass Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Bypass L1",
     "expr": "xupsBypassVoltage{instance=\"aux-ups01.cp.lsst.org\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "ups02-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Bypass L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Bypass L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups02-bypass",
     "select": [
      [
       { "params": [ "xupsBypassVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsBypassPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  }
 ]
}