{
 "title": "Puppet Report",
 "description": "Detailed information about Puppet report metrics",
 "tags": [ "Puppet" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(puppet_report, host)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(puppet_report, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Puppetdb status overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Puppet status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppetdb_node_report_status_count",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Failed hosts",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "puppet_report_resources{name=~\".*Failed.*\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Puppet Report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time since last report",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-puppet_report{host=\"$host\",environment=\"$environment\"} > -1"
    }
   ]
  },
  {
   "title": "Total of Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_events{host=\"$host\",environment=\"$environment\",name=\"Total\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_events{name=\"Failure\",host=\"$host\",environment=\"$environment\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_events{host=\"$host\",environment=\"$environment\",name=\"Success\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_resources{name=\"Total\",host=\"$host\",environment=\"$environment\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Changes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "puppet_report_changes{host=\"$host\",environment=\"$environment\"}"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duration (latest report)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(7,puppet_report_time{host=\"$host\",environment=\"$environment\"} > - 1)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources by status (latest report)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppet_report_resources{host=\"$host\",environment=\"$environment\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Puppet Reports over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duration (over time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "puppet_report_time{name=~\"Config retrieval|Total\",host=\"$host\",environment=\"$environment\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources by status (over time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppet_report_resources{host=\"$host\",environment=\"$environment\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}