{
 "title": "Strimzi Kafka Broker Throttling",
 "tags": [
  "Strimzi",
  "Kafka"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kafka_broker",
    "query": "kafka-local-storage-6, kafka-local-storage-7, kafka-local-storage-8"
   },
   { "name": "cluster", "query": "manke.ls, yagan.cp" }
  ]
 },
 "panels": [
  {
   "title": "Broker Produce Throttling Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_throttletimems{namespace=\"sasquatch\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"Produce\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Throttling Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_throttletimems{namespace=\"sasquatch\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"Produce\"}) by (request)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Fetch Purgatory Size Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_delayedoperationpurgatory_purgatorysize{namespace=\"sasquatch\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", delayedOperation=\"Fetch\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}