{
 "title": "Strimzi Kafka Broker Latency",
 "tags": [
  "Strimzi",
  "Kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "sasquatch" },
   { "name": "cluster", "query": "manke.ls, yagan.cp" },
   {
    "name": "kafka_broker",
    "query": "kafka-local-storage-6, kafka-local-storage-7, kafka-local-storage-8"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Time Produce Latency 99th",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"Produce\"}) by (request)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Time FetchConsumer Latency 99th",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"FetchConsumer\"}) by (request)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Time FetchFollower Latency 99th",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"FetchFollower\"}) by (request)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce Latency 99th per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"Produce\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FetchConsumer Latency 99th per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"FetchConsumer\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FetchFollower Latency 99th per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"FetchFollower\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"Produce\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FetchConsumer Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"FetchConsumer\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FetchFollower Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", prom_cluster=\"$cluster\", pod=~\"sasquatch-$kafka_broker\", container=\"kafka\", quantile=\"0.99\", request=\"FetchFollower\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}