---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: o11y
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    quotas:
      maxSize: 10Gi
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    quotas:
      maxSize: 1.00Ti
  preservePoolsOnDelete: false
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 3
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "4"
        memory: 4Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ceph-rgw-ingress
  namespace: rook-ceph
  annotations:
    cert-manager.io/issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  tls:
  - hosts:
    - s3.o11y.ls.lsst.org
    secretName: rook-ceph-rgw-ingress-tls
  rules:
  - host: s3.o11y.ls.lsst.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rook-ceph-rgw-lfa
            port:
              number: 80
