---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno-metrics
  labels:
    o11y.eu/monitor: enabled
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kyverno
      app.kubernetes.io/instance: kyverno
  endpoints:
  - port: metrics-port
    path: /metrics
    honorLabels: false
    scrapeTimeout: 10s
    interval: 15s
