---
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: yagan01.cp.lsst.org
  hostname_override: yagan01
  user: rke
  role:
  - controlplane
  - worker
  - etcd
  labels:
    role: storage-node
- address: yagan02.cp.lsst.org
  hostname_override: yagan02
  user: rke
  role:
  - controlplane
  - worker
  - etcd
  labels:
    role: storage-node
- address: yagan03.cp.lsst.org
  hostname_override: yagan03
  user: rke
  role:
  - controlplane
  - worker
  - etcd
  labels:
    role: storage-node
- address: yagan04.cp.lsst.org
  hostname_override: yagan04
  user: rke
  role:
  - controlplane
  - worker
  - etcd
  labels:
    role: storage-node
- address: yagan05.cp.lsst.org
  hostname_override: yagan05
  user: rke
  role:
  - controlplane
  - worker
  - etcd
  labels:
    role: storage-node
- address: yagan06.cp.lsst.org
  hostname_override: yagan06
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan07.cp.lsst.org
  hostname_override: yagan07
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan08.cp.lsst.org
  hostname_override: yagan08
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan09.cp.lsst.org
  hostname_override: yagan09
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan10.cp.lsst.org
  hostname_override: yagan10
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan11.cp.lsst.org
  hostname_override: yagan11
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan12.cp.lsst.org
  hostname_override: yagan12
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan13.cp.lsst.org
  hostname_override: yagan13
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan14.cp.lsst.org
  hostname_override: yagan14
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan15.cp.lsst.org
  hostname_override: yagan15
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan16.cp.lsst.org
  hostname_override: yagan16
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan17.cp.lsst.org
  hostname_override: yagan17
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan18.cp.lsst.org
  hostname_override: yagan18
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan19.cp.lsst.org
  hostname_override: yagan19
  user: rke
  role:
  - worker
  labels:
    role: storage-node
- address: yagan20.cp.lsst.org
  hostname_override: yagan20
  user: rke
  role:
  - worker
  labels:
    role: storage-node
services:
  etcd:
    image: ""
    extra_args:
      listen-metrics-urls: http://0.0.0.0:2381
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args:
      node-status-max-images: "-1"
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: "v1.23.7-rancher1-1"
private_registries: []
ingress:
  provider: none
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
restore:
  restore: false
  snapshot_name: ""
dns: null
