---
operator:
  labels:
    lsst.org/author: "fbegyn"
    lsst.org/discover: "true"
    lsst.org/monitor: "true"
    prometheus.io/scrape: "true"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
fluentbit:
  labels:
    lsst.org/author: "fbegyn"
    lsst.org/discover: "true"
    lsst.org/monitor: "true"
    prometheus.io/scrape: "true"
  image:
    # when using the fluent repo, drop the v prefix on the tag
    # repository: "cr.fluentbit.io/fluent/fluent-bit"
    tag: "v2.2.2"
  serviceMonitor:
    enable: true
  namespaceFluentBitCfgSelector:
    matchLabels:
      lsst.org/monitor: "true"
  output:
    opensearch:
      host: logging.opensearch
      port: 9200
      httpUser:
        valueFrom:
          secretKeyRef:
            name: fluentbit-logging-credentials
            key: username
      httpPassword:
        valueFrom:
          secretKeyRef:
            name: fluentbit-logging-credentials
            key: password
      logstashFormat: true
      logstashPrefix: kubernetes-logs
      tls:
        verify: false
      replaceDots: true
      traceError: true
      suppressTypeName: true
