---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/name: keycloak
          app.kubernetes.io/managed-by: Helm
  data:
    - secretKey: username
      remoteRef:
        key: Keycloak Credentials keycloak.tu.lsst.org
        property: username
    - secretKey: password
      remoteRef:
        key: Keycloak Credentials keycloak.tu.lsst.org
        property: password
