pull_request_rules:
  - name: backport to production branches
    conditions:
      - label=backport-production
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }} to {{ destination_branch }})"
        bot_account: {{ author }}
        labels:
            - base-{{ base }}
            - head-{{ head }}
            - dest-{{ destination_branch }}
        branches:
          - cp_production
          - ls_production
          - tu_production
