---
pull_request_rules:
  #
  # dev -> production rules
  #
  - name: promote dev -> production branch
    conditions:
      - base=dev
      - -label~=^shipit($|-)
      - author!=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }}"
        bot_account: "{{ author }}"
        labels:
          - from-dev
        assignees:
          - "{{ author }}"

  - name: promote dev(shipit) -> production branch
    conditions:
      - base=dev
      - label=shipit
      - author!=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }}"
        bot_account: "{{ author }}"
        labels:
          - from-dev
          - shipit
        assignees:
          - "{{ author }}"

  - name: promote dev(shipit-yes-i-really-really-mean-it) -> production branch
    conditions:
      - base=dev
      - label=shipit-yes-i-really-really-mean-it
      - author!=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }}"
        bot_account: "{{ author }}"
        labels:
          - from-dev
          - shipit-yes-i-really-really-mean-it
        assignees:
          - "{{ author }}"

  # mergify can't impersonate renovate[bot] as a PR author
  - name: promote renovate[bot] dev -> production branch
    conditions:
      - base=dev
      - -label~=^shipit($|-)
      - author=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }}"
        labels:
          - from-dev

  - name: promote renovate[bot] dev(shipit) -> production branch
    conditions:
      - base=dev
      - label=shipit
      - author=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }}"
        labels:
          - from-dev
          - shipit

  - name: promote renovate[bot] dev(shipit-yes-i-really-really-mean-it) -> production branch
    conditions:
      - base=dev
      - label=shipit-yes-i-really-really-mean-it
      - author=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }}"
        labels:
          - from-dev
          - shipit-yes-i-really-really-mean-it

  - name: request review on backports to production branch
    conditions:
      - base=production
      - label=from-dev
      - -label~=^shipit($|-)
    actions:
      request_reviews:
        teams:
          - "@lsst-it/cl-infra"

  - name: auto-merge shipit backports to production
    conditions:
      - base=production
      - label=from-dev
      - label~=^shipit($|-)
    actions:
      review:
        type: APPROVE
      merge:
        method: merge
  #
  # production -> cp_production rules
  #
  - name: promote production -> cp_production branch
    conditions:
      - base=production
      - -label~=^shipit($|-)
      - author!=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }}"
        bot_account: "{{ author }}"
        labels:
          - from-production
        assignees:
          - "{{ author }}"

  - name: promote production(shipit-yes-i-really-really-mean-it) -> cp_production branch
    conditions:
      - base=production
      - label=shipit-yes-i-really-really-mean-it
      - author!=renovate[bot]
    actions:
      backport:
        branches:
          - cp_production
        title: "{{ title }}"
        bot_account: "{{ author }}"
        labels:
          - from-production
          - shipit-yes-i-really-really-mean-it
        assignees:
          - "{{ author }}"

  # mergify can't impersonate renovate[bot] as a PR author
  - name: promote renovate[bot] production -> cp_production branch
    conditions:
      - base=production
      - label!=shipit-yes-i-really-really-mean-it
      - author=renovate[bot]
    actions:
      backport:
        branches:
          - cp_production
        title: "{{ title }}"
        labels:
          - from-production

  - name: promote renovate[bot] production(shipit-yes-i-really-really-mean-it) -> cp_production branch
    conditions:
      - base=production
      - label=shipit-yes-i-really-really-mean-it
      - author=renovate[bot]
    actions:
      backport:
        branches:
          - cp_production
        title: "{{ title }}"
        labels:
          - from-production
          - shipit-yes-i-really-really-mean-it

  - name: request review on backports to cp_production branch
    conditions:
      - base=cp_production
      - label=from-production
      - -label~=^shipit($|-)
    actions:
      request_reviews:
        teams:
          - "@lsst-it/cl-infra"

  - name: auto-merge shipit-yes-i-really-really-mean-it backports to production
    conditions:
      - base=cp_production
      - label=from-production
      - label=shipit-yes-i-really-really-mean-it
    actions:
      review:
        type: APPROVE
      merge:
        method: merge
