pull_request_rules:
  - name: backport to production branches
    conditions:
      - label=backport-production
    actions:
      label:
        add:
          - base-{{ base }}
          - head-{{ head }}
      backport:
        title: "{{ title }} (backport #{{ number }} to {{ destination_branch }})"
        branches:
          - cp_production
          - ls_production
          - tu_production
