pull_request_rules:
  - name: promote dev to master branch
    conditions:
      - and:
        - base=dev
        - merged
    actions:
      backport:
        branches:
          - master
        title: "{{ title }} (promote #{{ number }} to {{ destination_branch }})"
        merge_bot_account: "{{ author }}"
        labels:
          - from-dev
        assignees:
          - "{{ author }}"
