---
pull_request_rules:
  - name: promote dev to production branch
    conditions:
      - base=dev
      - label!=shipit
      - author!=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }} (promote #{{ number }} to {{ destination_branch }})"
        bot_account: "{{ author }}"
        labels:
          - from-dev
        assignees:
          - "{{ author }}"

  - name: promote dev(shipit) to production branch
    conditions:
      - base=dev
      - label=shipit
      - author!=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }} (promote #{{ number }} to {{ destination_branch }})"
        bot_account: "{{ author }}"
        labels:
          - from-dev
          - shipit
        assignees:
          - "{{ author }}"

  # mergify can't impersonate renovate[bot] as a PR author
  - name: promote renovate[bot] dev to production branch
    conditions:
      - base=dev
      - label!=shipit
      - author=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }} (promote #{{ number }} to {{ destination_branch }})"
        labels:
          - from-dev

  - name: promote renovate[bot] dev(shipit) to production branch
    conditions:
      - base=dev
      - label=shipit
      - author=renovate[bot]
    actions:
      backport:
        branches:
          - production
        title: "{{ title }} (promote #{{ number }} to {{ destination_branch }})"
        labels:
          - from-dev
          - shipit

  - name: request review on backports to production branch
    conditions:
      - base=production
      - label!=shipit
      - label=from-dev
    actions:
      request_reviews:
        teams:
          - "@lsst-it/cl-infra"

  - name: auto-merge shipit backports to production
    conditions:
      - base=production
      - label=from-dev
      - label=shipit
    actions:
      review:
        type: APPROVE
      merge:
        method: merge
