---
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length: false
  # do not obsess over comment formatting
  comments-indentation: false
  comments:
    require-starting-space: false
  indentation:
    spaces: consistent
    indent-sequences: consistent
  # ignore {{ .foo }} go templates
  braces: false
  quoted-strings:
    required: only-when-needed
  # do not warn over --- header
  document-start: false
