---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: backup
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPools:
    - failureDomain: host
      replicated:
        size: 3
  metadataServer:
    activeCount: 3
    activeStandby: true
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "4"
        memory: 4Gi
  preserveFilesystemOnDelete: false
---
apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  name: backup
  namespace: rook-ceph
spec:
  rados:
    pool: backup-data0
    # RADOS namespace where NFS client recovery data is stored in the pool.
    namespace: nfs-ns
  server:
    active: 1
    resources:
      limits:
        cpu: "3"
        memory: 8Gi
      requests:
        cpu: "3"
        memory: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-ceph-nfs
    ceph_daemon_type: nfs
    ceph_nfs: backup
    instance: a
    rook_cluster: rook-ceph
  name: rook-ceph-nfs-backup
  namespace: rook-ceph
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
  selector:
    app: rook-ceph-nfs
    ceph_daemon_type: nfs
    ceph_nfs: backup
    instance: a
    rook_cluster: rook-ceph
  type: LoadBalancer
