---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: https://connect.dev.lsst.org
      vaults:
        Dev: 1
        O11y: 2
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets
