---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: snmp-config
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
    - secretKey: snmpCommunity
      remoteRef:
        key: snmp community string
        property: credential
  target:
    template:
      templateFrom:
        - configMap:
            name: snmp-config-tmpl
            items:
              - key: snmp.yml
