---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-test-metrics
  namespace: kube-prometheus-stack
  labels:
    release:  kube-prometheus-stack
  annotations:
    o11y.eu/monitor: enabled
    o11y.eu/author: francis.begyn
spec:
  groups:
    - name: node-test-metrics
      rules:
        - alert: KubeTestRule
          expr: vector(1)
    - name: server-ping-response
      rules:
        - alert: ICMPPingFailed
          expr: min_over_time(probe_success{instance=~".*.ls.lsst.org"}[4m]) == 0
    - name: network-ping-response
      rules:
        - alert: ICMPPingFailed
          expr: min_over_time(probe_success{job="blackbox-csv-network"}[4m]) == 0
          labels:
            components: servers
            severity: warning
        - alert: ICMPPingFailed
          expr: min_over_time(probe_success{job="blackbox-csv-network"}[4m]) == 0
          for: 5m
          labels:
            components: network
            severity: critical
            receiver: ",squadcast,"
