{
 "title": "Strimzi Operators",
 "tags": [
  "Strimzi",
  "Kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "prom_cluster",
    "label": "K8s Cluster",
    "query": {
     "query": "label_values(kafka_server_replicamanager_leadercount,prom_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Custom Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka CRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"Kafka\",prom_cluster=\"$prom_cluster\"})"
    }
   ]
  },
  {
   "title": "User CRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"KafkaUser\",prom_cluster=\"$prom_cluster\"})"
    }
   ]
  },
  {
   "title": "Topics CRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"KafkaTopic\",prom_cluster=\"$prom_cluster\"})"
    }
   ]
  },
  {
   "title": "Connect CRs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"KafkaConnect\",prom_cluster=\"$prom_cluster\"})"
    }
   ]
  },
  {
   "title": "Mirror Maker 2 CRs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"KafkaMirrorMaker2\",prom_cluster=\"$prom_cluster\"})"
    }
   ]
  },
  {
   "title": "Mirror Maker CRs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"KafkaMirrorMaker\",prom_cluster=\"$prom_cluster\"})"
    }
   ]
  },
  {
   "title": "Bridge CRs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"KafkaBridge\",prom_cluster=\"$prom_cluster\"})"
    }
   ]
  },
  {
   "title": "Connector CRs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"KafkaConnector\",prom_cluster=\"$prom_cluster\"})"
    }
   ]
  },
  {
   "title": "Rebalance CRs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=\"KafkaRebalance\",prom_cluster=\"$prom_cluster\"})"
    }
   ]
  },
  { "title": "Reconciliations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Successful Reconciliation per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_successful_total{prom_cluster=\"$prom_cluster\"}[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Failed Reconciliation per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_failed_total{prom_cluster=\"$prom_cluster\"}[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Reconciliation without Lock per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_locked_total{prom_cluster=\"$prom_cluster\"}[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Started Reconciliation per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_total{prom_cluster=\"$prom_cluster\"}[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Periodical Reconciliation per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_periodical_total{prom_cluster=\"$prom_cluster\"}[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Maximum reconciliation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(strimzi_reconciliations_duration_seconds_max{prom_cluster=\"$prom_cluster\"}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{container=~\"user-operator|topic-operator|strimzi-cluster-operator\",prom_cluster=\"$prom_cluster\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{container=~\"user-operator|topic-operator|strimzi-cluster-operator\",prom_cluster=\"$prom_cluster\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{container=~\"user-operator|topic-operator|strimzi-cluster-operator\",prom_cluster=\"$prom_cluster\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}