---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  finalizers:
  - Opster
  name: logging
  namespace: opensearch
spec:
  bootstrap:
    resources: {}
  confMgmt: {}
  dashboards:
    enable: true
    basePath: "/dashboard"
    opensearchCredentialsSecret: {}
    replicas: 2
    labels:
      lsst.org/author: "fbegyn"
      lsst.org/monitor: "true"
      prometheus.io/scrape: "true"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    service:
      type: ClusterIP
    version: 2.11.1
  general:
    httpPort: 9200
    monitoring: {}
    serviceName: logging
    setVMMaxMapCount: true
    version: 2.11.1
    # pluginsList: ["repository-s3", "https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.11.1.0/prometheus-exporter-2.11.1.0.zip"]
  initHelper:
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "500m"
  nodePools:
  - component: cluster-manager
    replicas: 3
    diskSize: 10Gi
    labels:
      lsst.org/author: "fbegyn"
      lsst.org/monitor: "true"
      prometheus.io/scrape: "true"
    jvm: -Xmx2G -Xms2G
    resources:
      requests:
        memory: "4Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "1"
    roles:
    - cluster_manager
    persistence:
      emptyDir: {}
  - component: coordinators
    replicas: 3
    diskSize: 50Gi
    jvm: -Xmx2G -Xms2G
    labels:
      lsst.org/author: "fbegyn"
      lsst.org/monitor: "true"
      prometheus.io/scrape: "true"
    resources:
      requests:
        memory: "4Gi"
        cpu: "4"
      limits:
        memory: "4Gi"
        cpu: "4"
    roles:
    - coordinating
    persistence:
      emptyDir: {}
  - component: hot-nodes
    replicas: 3
    diskSize: 200Gi
    jvm: -Xmx2G -Xms2G
    labels:
      lsst.org/author: "fbegyn"
      lsst.org/monitor: "true"
      prometheus.io/scrape: "true"
    resources:
      requests:
        memory: "12Gi"
        cpu: "4"
      limits:
        memory: "12Gi"
        cpu: "4"
    additionalConfig:
      node.attr.temp: "hot"
    roles:
    - data
    - ingest
  - component: cold-nodes
    replicas: 3
    diskSize: 200Gi
    jvm: -Xmx2G -Xms2G
    labels:
      lsst.org/author: "fbegyn"
      lsst.org/monitor: "true"
      prometheus.io/scrape: "true"
    resources:
      requests:
        memory: "8Gi"
        cpu: "2"
      limits:
        memory: "8Gi"
        cpu: "2"
    additionalConfig:
      node.attr.temp: "cold"
    roles:
    - data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    cert-manager.io/cluster-issuer: letsencrypt-dev
  name: logging-os-api
  namespace: opensearch
spec:
  rules:
  - host: opensearch.ayekan.dev.lsst.org
    http:
      paths:
      - backend:
          service:
            name: logging-hot-nodes
            port:
              number: 9200
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - opensearch.ayekan.dev.lsst.org
    secretName: tls-logging-opensearch-ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: logging-dashboard
  namespace: opensearch
spec:
  rules:
  - host: opensearch.ayekan.dev.lsst.org
    http:
      paths:
      - backend:
          service:
            name: logging-dashboards
            port:
              number: 5601
        path: /dashboard(/|$)(.*)
        pathType: Prefix
  tls:
  - hosts:
    - opensearch.ayekan.dev.lsst.org
    secretName: tls-logging-opensearch-ingress
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fluentbit-logging-credentials
  namespace: opensearch
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
  - secretKey: username
    remoteRef:
      key: ayekan-logging-os-fluentbit
      property: username
  - secretKey: password
    remoteRef:
      key: ayekan-logging-os-fluentbit
      property: password
  target:
    creationPolicy: Owner
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: fluentbit-logging
  namespace: opensearch
spec:
  opensearchCluster:
    name: logging
  passwordFrom:
    name: fluentbit-logging-credentials
    key: password
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: fluentbit-logging-writer
  namespace: opensearch
spec:
  opensearchCluster:
    name: logging
  clusterPermissions:
  - cluster_composite_ops
  indexPermissions:
  - indexPatterns:
    - fluentbit-*
    - fluent-bit-*
    - logstash-*
    - log-stash-*
    - syslog-*
    - logs-*
    - cluster-logs-*
    - kubernetes-logs-*
    allowedActions:
    - crud
    - create_index
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchUserRoleBinding
metadata:
  name: fluentbit-logging-binding
  namespace: opensearch
spec:
  opensearchCluster:
    name: logging
  users:
  - fluentbit-logging
  roles:
  - fluentbit-logging-writer
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-logging-credentials
  namespace: opensearch
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
  - secretKey: username
    remoteRef:
      key: ayekan-logging-os-external
      property: username
  - secretKey: password
    remoteRef:
      key: ayekan-logging-os-external
      property: password
  target:
    creationPolicy: Owner
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: external-logging
  namespace: opensearch
spec:
  opensearchCluster:
    name: logging
  passwordFrom:
    name: external-logging-credentials
    key: password
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: external-logging-writer
  namespace: opensearch
spec:
  opensearchCluster:
    name: logging
  clusterPermissions:
  - cluster_composite_ops
  indexPermissions:
  - indexPatterns:
    - fluentbit-*
    - fluent-bit-*
    - logstash-*
    - log-stash-*
    - network-logs-*
    - syslog-*
    - rsyslog-*
    - host-*
    - logs-*
    allowedActions:
    - crud
    - create_index
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchUserRoleBinding
metadata:
  name: external-logging-binding
  namespace: opensearch
spec:
  opensearchCluster:
    name: logging
  users:
  - external-logging
  roles:
  - external-logging-writer
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: ayekan-logging
  namespace: opensearch
spec:
  opensearchCluster:
    name: logging
  description: "ayekan cluster tenant"
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: dev-logging
  namespace: opensearch
spec:
  opensearchCluster:
    name: logging
  description: "dev cluster tenant"
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: ls-logging
  namespace: opensearch
spec:
  opensearchCluster:
    name: logging
  description: "ls cluster tenant"
