---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rancher-bkp
  namespace: cattle-resources-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
    - secretKey: accessKey
      remoteRef:
        key: rancher-backup
        property: username
    - secretKey: secretKey
      remoteRef:
        key: rancher-backup
        property: password
