---
hostname: rancher.cp.lsst.org
ingress:
  tls:
    source: secret
  extraAnnotations:
    "cert-manager.io/cluster-issuer": letsencrypt
    "kubernetes.io/ingress.class": nginx
extraEnv:
  # version strings from https://github.com/rancher/charts/tree/dev-v2.9/charts/fleet
  - name: CATTLE_FLEET_MIN_VERSION
    value: 104.1.2+up0.10.6
