---
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
  hosts:
    - netbox.dev.lsst.org
  http:
    paths:
      - backend:
          service:
            name: netbox
            port:
              name:
              number: 8081
        path: /
        pathType: Prefix
  tls:
    - hosts:
        - netbox.dev.lsst.org
      secretName: nexus-dashboard-ingress-tls
