---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: onepassword-connect-token
            namespace: external-secrets
      connectHost: https://connect.ls.lsst.org
      vaults:
        k8s-common: 3
        k8s-ls: 2
        rancher.ls: 1
