apiVersion: v1
kind: Service
metadata:
  name: cnpg-loadbalancer
  namespace: cloudnativepg
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: cnpg-cluster
  type: LoadBalancer
