--
# Cluster Definition
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cloudnativepg
spec:
  instances: 3
  #startDelay: 300
  #stopDelay: 300  

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cnpg-cluster-app-user

  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-test-cbarria/"
      s3Credentials:
        accessKeyId:
          name: cnpg-aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-aws-creds
          key: ACCESS_SECRET_KEY
      wal:
          compression: gzip
    
    retentionPolicy: "30d" 

  superuserSecret:
    name: cnpg-cluster-superuser

# Resources and Storage Needs to be Adjust!
  
  storage:
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-backup-scheduled
  namespace: cloudnativepg
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-cluster
