apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
spec:
  instances: 3
  #startDelay: 300
  #stopDelay: 300

  bootstrap:
    recovery:
      source: cnpg-cluster

  externalClusters:
    - name: cnpg-cluster
      barmanObjectStore:
        destinationPath: "s3://cnpg-test-cbarria/"
        s3Credentials:
          accessKeyId:
            name: cnpg-aws-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: cnpg-aws-creds
            key: ACCESS_SECRET_KEY
        wal:
          compression: gzip

  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-test-cbarria/backup"
      s3Credentials:
        accessKeyId:
          name: cnpg-aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-aws-creds
          key: ACCESS_SECRET_KEY
      wal:
          compression: gzip

    retentionPolicy: "90d"
 
  superuserSecret:
    name: cnpg-cluster-superuser
  
# Resources and Storage needs tuning

  storage:
    size: 10Gi

  monitoring:
    enablePodMonitor: true

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-backup-scheduled
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-cluster
