---
image:
  tag: "v0.25.0"

replicas: 1

resources:
  limits:
    memory: 500Mi
  requests:
    memory: 500Mi

extraArgs:
  - "--config.file"
  - "/etc/snmp-exporter/snmp.yaml"
  - "--config.file"
  - "/etc/snmp-exporter/modules/snmp-*.yaml"

serviceMonitor:
  enabled: true
  selector:
    lsst.io/monitor: "true"

extraSecretMounts:
  - name: snmp-config
    mountPath: /etc/snmp-exporter
    secretName: snmp-config
    readOnly: true
    defaultmode: 420

extraVolumes:
  - name: snmp-exporter-modules
    projected:
      sources:
        - configMap:
            name: snmp-network
        - configMap:
            name: snmp-raritan
        - configMap:
            name: snmp-xups
        - configMap:
            name: snmp-schneider

extraVolumeMounts:
  - name: snmp-exporter
    volumeMounts:
      - name: snmp-exporter-modules
        mountPath: /etc/snmp-exporter/modules

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
  hosts:
    - snmp-exporter.o11y.dev.lsst.org
  tls:
    - secretName: tls-snmp-exporter-ingress
      hosts:
        - snmp-exporter.o11y.dev.lsst.org
