---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-xups
  namespace: monitoring
data:
  snmp-xups.yaml: |
    modules:
      xups:
        max_repetitions: 5
        walk:
        - 1.3.6.1.4.1.534.1.3.4
        - 1.3.6.1.4.1.534.1.4.4
        - 1.3.6.1.4.1.534.1.5.3
        get:
        - 1.3.6.1.4.1.534.1.2.1.0
        - 1.3.6.1.4.1.534.1.2.2.0
        - 1.3.6.1.4.1.534.1.2.3.0
        - 1.3.6.1.4.1.534.1.2.4.0
        - 1.3.6.1.4.1.534.1.2.5.0
        - 1.3.6.1.4.1.534.1.3.1.0
        - 1.3.6.1.4.1.534.1.4.2.0
        - 1.3.6.1.4.1.534.1.5.1.0
        - 1.3.6.1.4.1.534.1.6.1.0
        metrics:
        - name: xupsBatTimeRemaining
          oid: 1.3.6.1.4.1.534.1.2.1
          type: gauge
          help: Battery run time in seconds before UPS turns off due to low battery. -
            1.3.6.1.4.1.534.1.2.1
        - name: xupsBatVoltage
          oid: 1.3.6.1.4.1.534.1.2.2
          type: gauge
          help: Battery voltage as reported by the UPS meters. - 1.3.6.1.4.1.534.1.2.2
        - name: xupsBatCurrent
          oid: 1.3.6.1.4.1.534.1.2.3
          type: gauge
          help: Battery Current as reported by the UPS metering - 1.3.6.1.4.1.534.1.2.3
        - name: xupsBatCapacity
          oid: 1.3.6.1.4.1.534.1.2.4
          type: gauge
          help: Battery percent charge. - 1.3.6.1.4.1.534.1.2.4
        - name: xupsBatteryAbmStatus
          oid: 1.3.6.1.4.1.534.1.2.5
          type: gauge
          help: Gives the status of the Advanced Battery Management; batteryFloating(3)
            status means that the charger is temporarily charging the battery to its float
            voltage; batteryResting(4) is the state when the battery is fully charged
            and none of the other actions (charging/discharging/floating) is being done.
            - 1.3.6.1.4.1.534.1.2.5
          enum_values:
            1: batteryCharging
            2: batteryDischarging
            3: batteryFloating
            4: batteryResting
            5: unknown
        - name: xupsInputFrequency
          oid: 1.3.6.1.4.1.534.1.3.1
          type: gauge
          help: The utility line frequency in tenths of Hz. - 1.3.6.1.4.1.534.1.3.1
        - name: xupsInputPhase
          oid: 1.3.6.1.4.1.534.1.3.4.1.1
          type: gauge
          help: The number of the phase - 1.3.6.1.4.1.534.1.3.4.1.1
          indexes:
          - labelname: xupsInputPhase
            type: gauge
        - name: xupsInputVoltage
          oid: 1.3.6.1.4.1.534.1.3.4.1.2
          type: gauge
          help: The measured input voltage from the UPS meters in volts. - 1.3.6.1.4.1.534.1.3.4.1.2
          indexes:
          - labelname: xupsInputPhase
            type: gauge
        - name: xupsInputCurrent
          oid: 1.3.6.1.4.1.534.1.3.4.1.3
          type: gauge
          help: The measured input current from the UPS meters in amps. - 1.3.6.1.4.1.534.1.3.4.1.3
          indexes:
          - labelname: xupsInputPhase
            type: gauge
        - name: xupsInputWatts
          oid: 1.3.6.1.4.1.534.1.3.4.1.4
          type: gauge
          help: The measured input real power in watts. - 1.3.6.1.4.1.534.1.3.4.1.4
          indexes:
          - labelname: xupsInputPhase
            type: gauge
        - name: xupsOutputFrequency
          oid: 1.3.6.1.4.1.534.1.4.2
          type: gauge
          help: The measured UPS output frequency in tenths of Hz. - 1.3.6.1.4.1.534.1.4.2
        - name: xupsOutputPhase
          oid: 1.3.6.1.4.1.534.1.4.4.1.1
          type: gauge
          help: The number {1..3} of the output phase. - 1.3.6.1.4.1.534.1.4.4.1.1
          indexes:
          - labelname: xupsOutputPhase
            type: gauge
        - name: xupsOutputVoltage
          oid: 1.3.6.1.4.1.534.1.4.4.1.2
          type: gauge
          help: The measured output voltage from the UPS metering in volts. - 1.3.6.1.4.1.534.1.4.4.1.2
          indexes:
          - labelname: xupsOutputPhase
            type: gauge
        - name: xupsOutputCurrent
          oid: 1.3.6.1.4.1.534.1.4.4.1.3
          type: gauge
          help: The measured UPS output current in amps. - 1.3.6.1.4.1.534.1.4.4.1.3
          indexes:
          - labelname: xupsOutputPhase
            type: gauge
        - name: xupsOutputWatts
          oid: 1.3.6.1.4.1.534.1.4.4.1.4
          type: gauge
          help: The measured real output power in watts. - 1.3.6.1.4.1.534.1.4.4.1.4
          indexes:
          - labelname: xupsOutputPhase
            type: gauge
        - name: xupsBypassFrequency
          oid: 1.3.6.1.4.1.534.1.5.1
          type: gauge
          help: The bypass frequency in tenths of Hz. - 1.3.6.1.4.1.534.1.5.1
        - name: xupsBypassPhase
          oid: 1.3.6.1.4.1.534.1.5.3.1.1
          type: gauge
          help: The Bypass Phase, index for the table. - 1.3.6.1.4.1.534.1.5.3.1.1
          indexes:
          - labelname: xupsBypassPhase
            type: gauge
        - name: xupsBypassVoltage
          oid: 1.3.6.1.4.1.534.1.5.3.1.2
          type: gauge
          help: The measured UPS bypass voltage in volts. - 1.3.6.1.4.1.534.1.5.3.1.2
          indexes:
          - labelname: xupsBypassPhase
            type: gauge
        - name: xupsEnvAmbientTemp
          oid: 1.3.6.1.4.1.534.1.6.1
          type: gauge
          help: The reading of the ambient temperature in the vicinity of the UPS or SNMP
            agent. - 1.3.6.1.4.1.534.1.6.1
