---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: route53
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: it-dns-cp (aws)
        property: username
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: it-dns-cp (aws)
        property: password
