# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: andes01.cp.lsst.org
  user: rke
  role:
  - controlplane
  - worker
  - etcd
- address: andes02.cp.lsst.org
  user: rke
  role:
  - controlplane
  - worker
  - etcd
- address: andes03.cp.lsst.org
  user: rke
  role:
  - controlplane
  - worker
  - etcd
- address: andes04.cp.lsst.org
  user: rke
  role:
  - controlplane
  - worker
  - etcd
  #taints:
  #  - key: role
  #    value: storage-node
  #    effect: NoSchedule
- address: andes05.cp.lsst.org
  user: rke
  role:
  - controlplane
  - worker
  - etcd
  #taints:
  #  - key: role
  #    value: storage-node
  #    effect: NoSchedule
- address: andes06.cp.lsst.org
  user: rke
  role:
  - controlplane
  - worker
  - etcd
  #taints:
  #  - key: role
  #    value: storage-node
  #    effect: NoSchedule
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: "v1.17.14-rancher1-1"
private_registries: []
ingress:
  provider: none
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: metrics-server
  update_strategy:
    strategy: RollingUpdate
    rollingUpdate:
      maxUnavailable: 8
restore:
  restore: false
  snapshot_name: ""
dns: null
upgrade_strategy:
  max_unavailable_worker: 50%
  max_unavailable_controlplane: 1
  drain: true
  node_drain_input:
    force: true
    ignore_daemonsets: true
    delete_local_data: true
    grace_period: -1
    timeout: 60
