---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: ceph/ceph:v14.2.8
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 6
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  crashCollector:
    disable: false
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: ruka01
      devices:
      - name: sdb
        config:
          osdsPerDevice: "1"
    - name: ruka02
      devices:
      - name: sdb
        config:
          osdsPerDevice: "1"
    - name: ruka03
      devices:
      - name: sdb
        config:
          osdsPerDevice: "1"
    - name: ruka04
      devices:
      - name: nvme0n1
        config:
          osdsPerDevice: "1"
    - name: ruka05
      devices:
      - name: nvme0n1
        config:
          osdsPerDevice: "1"
    - name: ruka06
      devices:
      - name: nvme0n1
        config:
          osdsPerDevice: "1"
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
      tolerations:
      - key: role
        operator: Equal
        value: storage-node
        effect: NoSchedule
  disruptionManagement:
    managePodBudgets: true
