---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: source-db-replica-user
  namespace: cloudnativepg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: password
      remoteRef:
        key: cnpg-source-db-replica-user
        property: password
