{
 "title": "CCS-Database",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   },
   {
    "name": "persister",
    "query": "SHOW TAG VALUES WITH KEY = \"persister\""
   },
   {
    "name": "className",
    "query": "SHOW TAG VALUES WITH KEY = \"class_name\""
   },
   {
    "name": "queryName",
    "query": "SHOW TAG VALUES WITH KEY = \"query_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Batch Persister Stats (time, entries)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total data processed (1min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    },
    {
     "alias": "batch-$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "bcount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    }
   ]
  },
  {
   "title": "Mean batch size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    },
    {
     "alias": "batch-$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "bcount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    }
   ]
  },
  {
   "title": "Batch total processing time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "batch-$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "btime_tot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    },
    {
     "alias": "$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "time_tot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    }
   ]
  },
  {
   "title": "Batch processing time for entry ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "batch-$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "btime_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    },
    {
     "alias": "$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "time_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    }
   ]
  },
  {
   "title": "Processing (Incoming) Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "batch-$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "proc_queue_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingestion (Outgoing) Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "batch-$tag_persister",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "persister" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_persist",
     "select": [
      [
       { "params": [ "exec_queue_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "persister", "operator": "=~", "value": "/^$persister$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Session Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Session Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "connections",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_session",
     "select": [
      [
       { "params": [ "connect" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "alias": "flushes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_session",
     "select": [
      [
       { "params": [ "flush" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "alias": "transactions",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_session",
     "select": [
      [
       { "params": [ "transact" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "alias": "transactions ok",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_session",
     "select": [
      [
       { "params": [ "transact_success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "alias": "sessions opened",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_session",
     "select": [
      [
       { "params": [ "sess_open" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "alias": "sessions closed",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_session",
     "select": [
      [
       { "params": [ "sess_close" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Named Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Hits (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_query_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "query_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_named_queries",
     "select": [
      [
       { "params": [ "cache_hit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "query_name", "operator": "=~", "value": "/^$queryName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Misses (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_query_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "query_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_named_queries",
     "select": [
      [
       { "params": [ "cache_miss" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "query_name", "operator": "=~", "value": "/^$queryName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Puts (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_query_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "query_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_named_queries",
     "select": [
      [
       { "params": [ "cache_put" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "query_name", "operator": "=~", "value": "/^$queryName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Ececution Count (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_query_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "query_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_named_queries",
     "select": [
      [
       { "params": [ "exec_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "query_name", "operator": "=~", "value": "/^$queryName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Ececution Row Count (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_query_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "query_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_named_queries",
     "select": [
      [
       { "params": [ "exec_row_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "query_name", "operator": "=~", "value": "/^$queryName$/" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Execution time (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_query_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "query_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_named_queries",
     "select": [
      [
       { "params": [ "exec_time_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "query_name", "operator": "=~", "value": "/^$queryName$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Loads (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_class_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_cached_entities",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "class_name", "operator": "=~", "value": "/^$className$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Fetches (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_class_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_cached_entities",
     "select": [
      [
       { "params": [ "fetch" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "class_name", "operator": "=~", "value": "/^$className$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Inserts (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_class_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_cached_entities",
     "select": [
      [
       { "params": [ "insert" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "class_name", "operator": "=~", "value": "/^$className$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Updates (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_class_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_cached_entities",
     "select": [
      [
       { "params": [ "update" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "class_name", "operator": "=~", "value": "/^$className$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Failure (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_class_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_cached_entities",
     "select": [
      [
       { "params": [ "failure" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "class_name", "operator": "=~", "value": "/^$className$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Delete (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_class_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_cached_entities",
     "select": [
      [
       { "params": [ "delete" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "class_name", "operator": "=~", "value": "/^$className$/" }
     ]
    }
   ]
  },
  {
   "title": "Second Level Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Hits (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_class_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_second_level_cache",
     "select": [
      [
       { "params": [ "cache_hit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "class_name", "operator": "=~", "value": "/^$className$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Misses (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_class_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_second_level_cache",
     "select": [
      [
       { "params": [ "cache_miss" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "class_name", "operator": "=~", "value": "/^$className$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Puts (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_class_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "db_second_level_cache",
     "select": [
      [
       { "params": [ "cache_put" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "class_name", "operator": "=~", "value": "/^$className$/" }
     ]
    }
   ]
  }
 ]
}