{
 "title": "CCS-Tasks",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   },
   {
    "name": "AgentType",
    "query": "SHOW TAG VALUES WITH KEY = \"type\""
   },
   {
    "name": "task",
    "query": "SHOW TAG VALUES WITH KEY = \"task\""
   },
   {
    "name": "subsystem",
    "query": "SHOW TAG VALUES WITH KEY = \"name\"  where environment =~ /^$environment$/ and type =~ /^$AgentType$/"
   }
  ]
 },
 "panels": [
  {
   "title": "#Task Timing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "max execution time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "[[tag_name]]-$tag_task",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "periodic_tasks_metrics",
     "query": "SELECT max(\"time_max\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "time_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$AgentType$/" },
      { "condition": "AND", "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "max execution time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "[[tag_name]]-$tag_task",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "periodic_tasks_metrics",
     "query": "SELECT max(\"time_max\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "time_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$AgentType$/" },
      { "condition": "AND", "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Fraction of Period (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name-$tag_task",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "periodic_tasks_metrics",
     "query": "SELECT mean(\"percent_max\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "percent_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$AgentType$/" },
      { "condition": "AND", "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "average execution time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name-$tag_task",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "periodic_tasks_metrics",
     "query": "SELECT mean(\"time_avg\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "time_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$AgentType$/" },
      { "condition": "AND", "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "#Execution Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Long Executions (count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name-$tag_task",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "periodic_tasks_metrics",
     "query": "SELECT max(\"long\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "long" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$AgentType$/" },
      { "condition": "AND", "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Skipped Executions (count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name-$tag_task",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "periodic_tasks_metrics",
     "query": "SELECT max(\"skipped\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "skipped" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$AgentType$/" },
      { "condition": "AND", "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Exceptions (count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name-$tag_task",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "periodic_tasks_metrics",
     "query": "SELECT max(\"exceptions\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "exceptions" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$AgentType$/" },
      { "condition": "AND", "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Final Exceptions (count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name-$tag_task",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "periodic_tasks_metrics",
     "query": "SELECT max(\"final\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "final" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$AgentType$/" },
      { "condition": "AND", "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  { "title": "Scheduler Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Scheduler Thread Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name $tag_scheduler",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "scheduler::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "scheduler::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "scheduler_metrics",
     "query": "SELECT mean(\"percent_avg\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ \n AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "thread_pool_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Scheduler Thread Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name $tag_scheduler",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "scheduler::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "scheduler::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "scheduler_metrics",
     "query": "SELECT mean(\"percent_avg\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ \n AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "queue_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Scheduler Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name $tag_scheduler",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "scheduler::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "scheduler::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "scheduler_metrics",
     "query": "SELECT mean(\"percent_avg\") FROM \"periodic_tasks_metrics\" WHERE (\"environment\" =~ /^$environment$/ AND \"type\" =~ /^$AgentType$/ \n AND \"name\" =~ /^$subsystem$/) AND $timeFilter GROUP BY time(1m), \"task\", \"name\" fill(0)",
     "select": [
      [
       { "params": [ "active_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  }
 ]
}