image:
  tag: "v0.24.0"

replicas: 1

resources:
  limits:
    memory: 500Mi
  requests:
    memory: 500Mi

serviceMonitor:
  enabled: true
  selfMonitor:
    enabled: true
    labels:
      lsst.io/monitor: "true"
  defaults:
    labels:
      lsst.io/monitor: "true"
  targets:
    - name: googlehttpcheck
      url: https://google.com
      hostname: google.com
      interval: 60s
      module: http_2xx

# TODO: Error: UPGRADE FAILED: release blackbox-exporter failed, and has been
# rolled back due to atomic being set: failed to create resource: admission
# webhook "prometheusrulemutate.monitoring.coreos.com" denied the request: Cannot
# unmarshal rules from spec
prometheusRule:
  enabled: false
  labels:
    lsst.io/discover: "true"

extraConfigmapMounts: []
extraSecretMounts: []

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
  hosts:
    - host: blackbox-exporter.o11y.dev.lsst.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-snmp-exporter-ingress
      hosts:
        - blackbox-exporter.o11y.dev.lsst.org

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
    icmp:
      prober: icmp
      icmp:
        preferred_ip_protocol: "ip4"
