# yamllint disable-file
---
# Source: velero/templates/backupstoragelocation.yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: velero-2.29.7
spec:
  default: true
  provider: velero.io/aws
  accessMode: ReadWrite
  objectStorage:
    bucket: "it-backup"
    prefix: "gaw"
  config:
    profile: default
    insecureSkipTLSVerify: "true"
    s3ForcePathStyle: 'true'
    s3Url: "https://it-s3.cp.lsst.org"
    publicUrl: "https://it-s3.cp.lsst.org"
    region: "us-east-1"
