extraEnv: |
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"

ingress:
  enabled: true
  servicePort: https
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hostname: ${KEYCLOAK_INGRESS}
  tls: true

auth:
  adminUser: admin
  existingSecret: keycloak-admin
  passwordSecretKey: password

tls:
  ## @param tls.enabled Enable TLS encryption. Required for HTTPs traffic.
  ##
  enabled: true

tls: true
  extraTls:
  - hosts:
    - keycloak.kind.cluster
    secretName: keycloak.kind.cluster-tls

externalDatabase:
  host: ${POSTGRES_HOST}
  port: 5432
  user: keycloak
  database: keycloak
  existingSecret: keycloak-pg
  existingSecretPasswordKey: password
  