---
# yamllint disable rule:quoted-strings
name: check fleet symlinks

"on":
  - push

jobs:
  fleet-symlinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: check fleet symlinks
        run: go run ./utils/checksymlinks.go --path fleet
