---
# yamllint disable rule:quoted-strings
name: yamllint

"on":
  - push

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run yamllint
        uses: bewuethr/yamllint-action@v1
